Repository cert-manager/website, pull requests merged in 2019-12, with the labels that each got.

#46 Correct small typo
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#47 Update _index.md
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#48 doc: fixed typo and minor rephrasing
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#52 Spelling fix requets->requests
  content/en/docs/concepts/certificaterequest.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#54 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#61 Clarify that Vault tokens are not refreshed
  content/en/docs/configuration/vault.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#57 Added more details for the dns01/azuredns.md. Checked current commands
  content/en/docs/configuration/acme/dns01/azuredns.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#59 Update certificate.md
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#37 Adds ACME external account binding docs
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#63 Add configuration for release-0.13
  config/_default/params.toml
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  scripts/gendocs/generate
  scripts/gendocs/templates/pkg.tpl
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/M

#64 Use the correct hostname when linking to files in ACME tutorial
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#67 Correct CertificateRequest documentation
  content/en/docs/concepts/certificaterequest.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
