Repository cert-manager/website, pull requests merged in 2019-11, with the labels that each got.

#5 Fixup globbing for spellchecker
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#7 Re-orders sidebar and improves release note titles
  content/en/docs/concepts/ca-injector.md
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/issuer.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/external.md
  content/en/docs/release-notes/release-notes-0.1.md
  content/en/docs/release-notes/release-notes-0.10.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/release-notes/release-notes-0.2.md
  content/en/docs/release-notes/release-notes-0.3.md
  content/en/docs/release-notes/release-notes-0.4.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.8.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/csi.md
  content/en/docs/usage/ingress.md
  content/en/docs/usage/istio.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#6 Fixup spelling
  .spelling
  content/en/docs/concepts/ca-injector.md
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/issuer.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/acme-dns.md
  content/en/docs/configuration/acme/dns01/digitalocean.md
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/configuration/acme/dns01/rfc2136.md
  content/en/docs/configuration/acme/dns01/route53.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/external.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/vault.md
  content/en/docs/configuration/venafi.md
  content/en/docs/contributing/contributing-flow.md
  content/en/docs/contributing/e2e.md
  content/en/docs/contributing/external-issuers.md
  content/en/docs/contributing/kind.md
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-0.1.md
  content/en/docs/release-notes/release-notes-0.10.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/release-notes/release-notes-0.2.md
  content/en/docs/release-notes/release-notes-0.3.md
  content/en/docs/release-notes/release-notes-0.4.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.8.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/acme/dns-validation.md
  content/en/docs/tutorials/acme/http-validation.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/acme/migrating-from-kube-lego.md
  content/en/docs/tutorials/backup.md
  content/en/docs/tutorials/uninstall/kubernetes.md
  content/en/docs/tutorials/uninstall/openshift.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/_index.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/csi.md
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#19 Fixes configuration acme dns01 route53 iam policy json
  .spelling
  content/en/docs/configuration/acme/dns01/route53.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#20 Adds cert-manager logo favicons
  static/favicons/android-144x144.png
  static/favicons/android-192x192.png
  static/favicons/android-36x36.png
  static/favicons/android-48x48.png
  static/favicons/android-72x72.png
  static/favicons/android-96x96.png
  static/favicons/apple-touch-icon-180x180.png
  static/favicons/favicon-1024.png
  static/favicons/favicon-16x16.png
  static/favicons/favicon-256.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
  static/favicons/pwa-192x192.png
  static/favicons/pwa-512x512.png
  static/favicons/tile150x150.png
  static/favicons/tile310x150.png
  static/favicons/tile310x310.png
  static/favicons/tile70x70.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#16 Adds key usages and update usage certificate yaml
  .spelling
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#14 Adds ACME Orders and Challenges to concepts
  .spelling
  content/en/docs/concepts/acme-orders-challenges.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#15 Adds version compatibility
  content/en/docs/concepts/project-maturity.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#17 Adds faq acme debug
  content/en/docs/faq/_index.md
  content/en/docs/faq/acme.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#18 Adds configuration acme dns01 webhook
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/webhook.md
  content/en/docs/contributing/dns-providers.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#22 Bump version strings for v0.12.0-beta.0 release
  config/_default/params.toml
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/usage/certificate.md
  scripts/gendocs/generate
  scripts/update-content
Labels: approved, dco-signoff: yes, lgtm, size/M

#24 Re-order issuer list in bar for better readability
  content/en/docs/configuration/acme/_index.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/external.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#25 Adds more ACME solver docs
  .spelling
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#28 Improvements to gen-crd-api-reference-docs configuration
  scripts/bin/gen-crd-api-reference-docs
  scripts/gendocs/config.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#26 Fix up Kubernetes auth 'mountPath' field
  content/en/docs/configuration/vault.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#29 Update install guide for v0.12.0-beta.1
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#36 Updated remaining incorrect references to venafi cloud enrollment pages
  content/en/docs/configuration/venafi.md
  content/en/docs/tutorials/venafi/venafi.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#30 Adds back in OpenFaaS
  .spelling
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#32 Adds istio gateway usage
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#38 Add homepage content
  content/en/_index.html
Labels: approved, dco-signoff: yes, lgtm, size/S

#31 Adds integration with garden usage
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#27 Upgrade guide
  content/en/docs/installation/uninstall/_index.md
  content/en/docs/installation/uninstall/kubernetes.md
  content/en/docs/installation/uninstall/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-0.10-0.11.md
  content/en/docs/installation/upgrading/upgrading-0.2-0.3.md
  content/en/docs/installation/upgrading/upgrading-0.3-0.4.md
  content/en/docs/installation/upgrading/upgrading-0.4-0.5.md
  content/en/docs/installation/upgrading/upgrading-0.5-0.6.md
  content/en/docs/installation/upgrading/upgrading-0.6-0.7.md
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/installation/upgrading/upgrading-0.8-0.9.md
  content/en/docs/installation/upgrading/upgrading-0.9-0.10.md
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#34 Spelling and grammar
  .spelling
  content/en/docs/concepts/acme-orders-challenges.md
  content/en/docs/concepts/ca-injector.md
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/issuer.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/_index.md
  content/en/docs/configuration/acme/_index.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/acme-dns.md
  content/en/docs/configuration/acme/dns01/azuredns.md
  content/en/docs/configuration/acme/dns01/digitalocean.md
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/configuration/acme/dns01/route53.md
  content/en/docs/configuration/acme/dns01/webhook.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/external.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/vault.md
  content/en/docs/configuration/venafi.md
  content/en/docs/faq/kubed.md
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/release-notes/_index.md
  content/en/docs/usage/_index.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/csi.md
  content/en/docs/usage/ingress.md
  content/en/docs/usage/istio.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#33 Adds 0.12 upgrade guide
  content/en/docs/installation/upgrading/upgrading-0.11.12.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#39 Add Google Analytics tracking ID
  config/_default/config.toml
  scripts/build-release
  scripts/server-release
  scripts/verify-release
Labels: approved, dco-signoff: yes, lgtm, size/S

#40 Copy _redirects file into public/ directory
  scripts/build
Labels: approved, dco-signoff: yes, lgtm, size/XS

#23 Removes all TODOs
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/vault.md
  content/en/docs/configuration/venafi.md
  content/en/docs/contributing/external-issuers.md
  content/en/docs/contributing/release-process.md
  content/en/docs/faq/acme.md
  content/en/docs/installation/compatibility.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/ingress.md
  layouts/shortcodes/include.html
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/L

#43 Add release notes for v0.12
  config/_default/config.toml
  content/en/docs/installation/upgrading/upgrading-0.11-0.12.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-0.12.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#44 Add no_list: true to release-notes page
  content/en/docs/release-notes/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#45 Remove -beta.1 suffix from version strings
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/S
