Repository cert-manager/website, pull requests merged in 2020-02, with the labels that each got.

#99 Changed Helm link to helm.io
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#95 Fix CA reference, was `letsencrypt-prod`, should be `ca-issuer`
  content/en/docs/concepts/certificaterequest.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#100 doc: inconsistent resource name
  content/en/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#105 Make kubectl example have the same secret name
  content/en/docs/tutorials/acme/dns-validation.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#106 Remove commonName where possible
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/tutorials/acme/dns-validation.md
  content/en/docs/tutorials/acme/http-validation.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#108 Correct a typo in ca.md
  content/en/docs/configuration/ca.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#111 Removing Helmfile install as it has fallen behind
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#110 Update Helm install instructions
  .spelling
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#113 Add note on update-crds.sh
  content/en/docs/contributing/kind.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#112 Fix typo in Generating CRDs script
  content/en/docs/contributing/kind.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#116 Bump version strings for v0.13.1
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#122 cleanup white noise
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/release-notes/release-notes-0.12.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#121 Fix spelling errors
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#104 Add search
  assets/js/search.js
  assets/scss/_search.scss
  config/_default/config.toml
  content/en/images/search-by-algolia-light-background.svg
  layouts/partials/navbar.html
  layouts/partials/scripts.html
  package-lock.json
  package.json
  scripts/index
Labels: approved, dco-signoff: yes, lgtm, size/XL

#96 Fixed variable in AzureDNS documentation
  content/en/docs/configuration/acme/dns01/azuredns.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#109 Update ingress.md to improve readability
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#119 Fix `helm install` command output
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#125 Make Algolia logo link to algolia.com
  assets/js/search.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#114 Add more documentation on e2e tests
  content/en/docs/contributing/e2e.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#126 Fix spelling error
  content/en/docs/concepts/project-maturity.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#128 Add description of Ingress annotations for out-of-tree Issuers
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
