Repository cert-manager/website, pull requests merged in 2020-01, with the labels that each got.

#77 Remove '-' in matchLabels
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#81 Community How-To Guide contributions
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#82 Adds video meeting URLs for standup and bi-weekly developer
  content/en/docs/contributing/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#83 doc: typo
  content/en/docs/installation/compatibility.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#79 Fixes the minimum Kubernetes version for cert-manager (0.12 -> 1.12)
  content/en/docs/concepts/project-maturity.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#66 fix DEPRECIATED typo
  content/en/docs/installation/upgrading/upgrading-0.10-0.11.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#80 fix misspelled word in docs
  content/en/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#71 add webhook link for INWX
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#86 Update installation docs for v0.13.0
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#78 Add documentation about scoped cloudflare api tokens
  content/en/docs/configuration/acme/dns01/cloudflare.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#89 Update install URL for CRDs
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#93 Fixing duraton -> duration typo
  content/en/docs/concepts/certificaterequest.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#94 Include cert-manager-webhook-civo in the docs
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
