Repository cert-manager/website, pull requests merged in 2020-09, with the labels that each got.

#307 Note release of Helm v3.3.1
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#308 Document Cloudflare blacklisted TLDs
  .spelling
  content/en/docs/configuration/acme/dns01/cloudflare.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#299 v1.0 release and upgrade notes
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-0.16-1.0.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.0.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#310 Move v1.0 docs into master
  .spelling
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/issuer.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/_index.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/acme-dns.md
  content/en/docs/configuration/acme/dns01/akamai.md
  content/en/docs/configuration/acme/dns01/azuredns.md
  content/en/docs/configuration/acme/dns01/cloudflare.md
  content/en/docs/configuration/acme/dns01/digitalocean.md
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/configuration/acme/dns01/rfc2136.md
  content/en/docs/configuration/acme/dns01/route53.md
  content/en/docs/configuration/acme/dns01/webhook.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/vault.md
  content/en/docs/configuration/venafi.md
  content/en/docs/faq/kubed.md
  content/en/docs/faq/troubleshooting.md
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-0.16-1.0.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.0.md
  content/en/docs/tutorials/acme/dns-validation.md
  content/en/docs/tutorials/acme/example/production-issuer.yaml
  content/en/docs/tutorials/acme/example/staging-issuer.yaml
  content/en/docs/tutorials/acme/http-validation.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/acme/migrating-from-kube-lego.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/csi.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#309 Configure website for the v1.0 release
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#306 Add documentation for GKE workload identity
  .spelling
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#311 Fix link to 0.16 to 1.0 upgrade guide
  content/en/docs/installation/upgrading/upgrading-0.16-1.0.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#314 Link to Kubernetes 1.19 API docs
  scripts/gendocs/config.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#317 Fix branch configuration for 0.16
  scripts/update-content
Labels: approved, dco-signoff: yes, lgtm, size/XS

#318 Update OpenShift installation documentation for V1 release
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#322 Update for v1.0.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#312 Minor doc fix
  content/en/docs/release-notes/release-notes-1.0.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#323 Update Openshift installation docs to install cert-manager v1.0.1
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#313 Add docs about ingress controller support for default TLS cert
  .spelling
  content/en/docs/faq/kubed.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#315 Use the latest upstream version of gen-crd-api-reference-docs
  .go-version
  scripts/bin/gen-crd-api-reference-docs
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, lgtm, size/M

#319 Add link to AWS KmsIssuer external issuer
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#325 Fix help
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#282 Update release-process documentation
  .spelling
  content/en/docs/contributing/contributing-flow.md
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#329 Expanded documentation for cainjector
  .spelling
  content/en/docs/concepts/ca-injector.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#331 Update installation instructions for v1.0.2
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#333 Write more contributor docs
  .spelling
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/building.md
  content/en/docs/contributing/contributing-flow.md
  content/en/docs/contributing/crds.md
  content/en/docs/contributing/e2e.md
  content/en/docs/contributing/kind.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#327 Improve language on which DNS solvers are called
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
