Repository cert-manager/website, pull requests merged in 2020-10, with the labels that each got.

#276 Document more GKE LB issues
  content/en/docs/faq/acme.md
  content/en/docs/tutorials/acme/http-validation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#339 Fix meetings page's markdown
  content/en/docs/contributing/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#342 Webhook known problems, solutions and debug techniques
  content/en/docs/concepts/webhook.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#343 An FAQ about the Kubernetes CertificateSigningRequest API
  content/en/docs/faq/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#332 Add myself to cert-manager website approvers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#341 Fix typo of troubleshooting.md
  content/en/docs/faq/troubleshooting.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#345 Use correct fields in HTTP01 challenge docs
  content/en/docs/configuration/acme/http01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#347 Update installation instructions for v1.0.3
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#348 Add a section on debugging ACME issuer status
  content/en/docs/faq/acme.md
  content/en/docs/faq/troubleshooting.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#355 Add infomaniak webhook
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#352 Fix confusing part about ingress class defaults
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#351 Add more common questions
  .spelling
  content/en/docs/faq/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#356 nit: use proper case for "Cloudflare"
  content/en/docs/configuration/acme/dns01/cloudflare.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#358 Change versions to v1.0.4
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S
