Repository cert-manager/website, pull requests merged in 2020-07, with the labels that each got.

#233 Document secret ownership behaviour
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#240 Fixed link pattern to CRDs on uninstall page
  content/en/docs/installation/uninstall/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#246 Fix a typo in "Certificate Resources" document page
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#247 Improve grammar and correct typos
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#248 Added documentation on create cr command
  .spelling
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#252 Add CertificateRequest to spelling
  .spelling
Labels: approved, dco-signoff: yes, lgtm, size/XS

#251 docs(version): bump cert-manager version to 0.15.2
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#238 Do not install cert-manager in kube-system in the lego guide
  content/en/docs/tutorials/acme/migrating-from-kube-lego.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#254 Add DNS01RecursiveNameserversOnly to docs
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#257 document the case of SOA records being filtered
  content/en/docs/configuration/acme/dns01/cloudflare.md
  content/en/docs/faq/acme.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#239 v0.16 release notes
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-0.16.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#259 Make v0.16 the main version
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#260 Update versions to 0.16.0
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#261 Fix bullet points in release notes
  content/en/docs/release-notes/release-notes-0.16.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#263 Document issues with kubectl apply
  .spelling
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#265 ✏️ Minor typo
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#266 Fix link to kubectl on Darwin
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#258 Added more troubleshooting info
  content/en/docs/faq/acme.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#267 Add notice on sub-charting cert-manager
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#269 Adds kubed example for syncing secrets
  content/en/docs/faq/kubed.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#268 Document webhook compatibility issue with EKS
  .spelling
  content/en/docs/installation/compatibility.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/S
