Repository cert-manager/website, pull requests merged in 2020-04, with the labels that each got.

#169 Fix typo in the docs
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#170 Fix typo.
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#173 Added example secret yaml
  content/en/docs/configuration/acme/dns01/digitalocean.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#180 Fix typo
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#179 docs: Update to v0.14.2
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#175 corrects auth values for tokenSecretRef
  content/en/docs/configuration/vault.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#181 Add documentation for private key rotation feature
  content/en/docs/usage/certificate.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#190 Fix typo in ClusterIssuer example to match comment
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#191 docs: Update to v0.14.3
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#188 Update NPM dependencies
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#184 Add note on use of --purge
  content/en/docs/installation/uninstall/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
