Repository cert-manager/website, pull requests merged in 2020-11, with the labels that each got.

#353 Create externalloadbalancer.md
  .spelling
  content/en/docs/configuration/externalloadbalancer.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#362 Adding spacing to render bulleted list correctly
  content/en/docs/contributing/building.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#364 Use the GUID zone for venafi Cloud example
  content/en/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#366 Add preferredChain also into the ACME config docs
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#370 Add link to Cloudflare Origin CA Issuer
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#361 Clarify the format of tls.crt and ca.crt
  content/en/docs/concepts/certificate.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#368 Update _index.md fixes #367
  content/en/docs/concepts/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#346 Document how to configure Venafi TPP access-token authentication
  content/en/docs/configuration/venafi.md
  content/en/docs/contributing/building.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#374 Fix typo: remove duplicated 'the'
  content/en/docs/faq/acme.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#375 Add Scaleway webhook
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#372 Update _index.md
  content/en/docs/contributing/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#373 Make the year of the date clear on docs/configuration/acme/ page
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#363 Prepare the release notes + version change for 1.1.0
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.0-1.1.md
  content/en/docs/release-notes/release-notes-1.1.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#376 Publish v1.1 docs
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#379 Added needed escape to second sed expression since
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#377 Release note with warning of deprecated --renew-before-expiry-duration flag
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S
