Repository cert-manager/website, pull requests merged in 2020-03, with the labels that each got.

#133 Add link to new Webhook for Gandi DNS
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#134 Add Oracle Cloud Infrastructure as a supported DNS provider through a webhook
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#129 Fix typo in route53.md
  content/en/docs/configuration/acme/dns01/route53.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#140 Add meyskens to approvers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#131 Fix docs by mentioning the 2 separate annotations
  content/en/docs/concepts/ca-injector.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#141 Add CAA Rechecking Bug to FAQ
  .spelling
  content/en/docs/faq/acme.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#102 Add key field under privateKeySecretRef
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#147 Add 'next' version documentation
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#145 Add upgade instructions for v0.14
  content/en/docs/installation/upgrading/upgrading-0.13-0.14.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#149 Add release notes for v0.14
  .spelling
  content/en/docs/concepts/webhook.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/release-notes/release-notes-0.14.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#138 Add documentation on the legacy release
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#151 Merge master into release-next
  config/_default/params.toml
  content/en/docs/release-notes/release-notes-0.14.md
  content/en/docs/tutorials/acme/ingress.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#152 Update version strings in config for v0.14
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#153 Merge 'release-next' into master and make v0.14 default version
  .spelling
  config/_default/params.toml
  content/en/docs/concepts/webhook.md
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-0.13-0.14.md
  content/en/docs/release-notes/release-notes-0.14.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/L

#156 Reorder release notes pages and add missing v0.14 link
  content/en/docs/installation/upgrading/upgrading-0.10-0.11.md
  content/en/docs/installation/upgrading/upgrading-0.11-0.12.md
  content/en/docs/installation/upgrading/upgrading-0.12-0.13.md
  content/en/docs/installation/upgrading/upgrading-0.13-0.14.md
  content/en/docs/installation/upgrading/upgrading-0.2-0.3.md
  content/en/docs/installation/upgrading/upgrading-0.3-0.4.md
  content/en/docs/installation/upgrading/upgrading-0.4-0.5.md
  content/en/docs/installation/upgrading/upgrading-0.5-0.6.md
  content/en/docs/installation/upgrading/upgrading-0.6-0.7.md
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/installation/upgrading/upgrading-0.8-0.9.md
  content/en/docs/installation/upgrading/upgrading-0.9-0.10.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-0.1.md
  content/en/docs/release-notes/release-notes-0.10.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/release-notes/release-notes-0.12.md
  content/en/docs/release-notes/release-notes-0.13.md
  content/en/docs/release-notes/release-notes-0.14.md
  content/en/docs/release-notes/release-notes-0.2.md
  content/en/docs/release-notes/release-notes-0.3.md
  content/en/docs/release-notes/release-notes-0.4.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.8.md
  content/en/docs/release-notes/release-notes-0.9.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#157 Ensure public/ directory exists in scripts/index
  scripts/index
Labels: approved, dco-signoff: yes, lgtm, size/XS

#159 Fix list Markdown formatting
  content/en/docs/installation/upgrading/upgrading-0.13-0.14.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#132 Use DocSearch
  assets/js/search.js
  layouts/partials/head.html
  layouts/partials/scripts.html
Labels: approved, dco-signoff: yes, lgtm, size/M

#162 Change K8S verification example kind
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#127 No need to create namespace
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#115 Add custom fields for venafi
  content/en/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#166 Add doc for http solver ingressTemplate
  content/en/docs/configuration/acme/http01/_index.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#164 Includes the CRL Distribution Points option
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#168 Update installation docs for v0.14.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, lgtm, size/S
