Repository cert-manager/website, pull requests merged in 2020-12, with the labels that each got.

#383 Small fixes for 1.1 release notes
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.1.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#381 Updating section for MatchLabels
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#385 Mention how to let people know that a PR in in progress
  content/en/docs/contributing/contributing-flow.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#389 fixed version typo in project-maturity.md
  content/en/docs/concepts/project-maturity.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#390 docs(installation/kubernetes): update kubeprod info
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#350 Add Docs to support using Managed Identity
  content/en/docs/configuration/acme/dns01/azuredns.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#392 Remove Helm 2 instructions
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/uninstall/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#393 Update acme.md
  .spelling
  content/en/docs/faq/acme.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#394 Add link to the Google CAS Issuer
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#395 Adding IBM Cloud Internet Service (ibmcis) to the webhook list
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
