Repository cert-manager/website, pull requests merged in 2020-08, with the labels that each got.

#274 Add new spells from release
  .spelling
Labels: approved, dco-signoff: yes, lgtm, size/XS

#272 Small typo fix: sates -> states
  content/en/docs/contributing/external-issuers.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#279 Adds reference to cluster resource namespace in configuration
  content/en/docs/configuration/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#280 Update digitalocean.md
  content/en/docs/configuration/acme/dns01/digitalocean.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#281 Update versions to 0.16.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#285 State DigitalOcean access tokens need write access
  content/en/docs/configuration/acme/dns01/digitalocean.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#286 Update documentation to reflect current state of kubectl
  content/en/docs/installation/upgrading/upgrading-0.15-0.16.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#270 Add docs for usage keys
  content/en/docs/usage/csi.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#294 Add doc reference for AWS Private CA issuer
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#296 Add a page for Prometheus metrics
  .spelling
  content/en/docs/usage/prometheus-metrics.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#298 fix(_index.md): typo
  content/en/docs/configuration/acme/http01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#297 Improve route53 documentation
  content/en/docs/configuration/acme/dns01/route53.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#291 Add doc about status certificate command
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#290 Improve Route53 instructions.
  content/en/docs/configuration/acme/dns01/route53.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#304 Add examples for how to write “cert-manager”
  content/en/docs/faq/style.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#303 Update examples and references to v1alpha2 field names
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/issuer.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/_index.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/acme-dns.md
  content/en/docs/configuration/acme/dns01/akamai.md
  content/en/docs/configuration/acme/dns01/azuredns.md
  content/en/docs/configuration/acme/dns01/cloudflare.md
  content/en/docs/configuration/acme/dns01/digitalocean.md
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/configuration/acme/dns01/rfc2136.md
  content/en/docs/configuration/acme/dns01/route53.md
  content/en/docs/configuration/acme/dns01/webhook.md
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/configuration/vault.md
  content/en/docs/configuration/venafi.md
  content/en/docs/faq/kubed.md
  content/en/docs/faq/troubleshooting.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/tutorials/acme/dns-validation.md
  content/en/docs/tutorials/acme/example/production-issuer.yaml
  content/en/docs/tutorials/acme/example/staging-issuer.yaml
  content/en/docs/tutorials/acme/http-validation.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/acme/migrating-from-kube-lego.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/csi.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#301 Clean up EAB docs and add docs about reusing ACME accounts
  content/en/docs/configuration/acme/_index.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/M
