Repository cert-manager/website, pull requests merged in 2020-05, with the labels that each got.

#183 Explain usage of cnameStrategy: Follow in greater detail
  .spelling
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#193 v0.15 prepatations
  .spelling
  content/en/.gitignore
  content/en/docs/configuration/acme/_index.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-0.14-0.15.md
  content/en/docs/release-notes/release-notes-0.15.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#199 Edits for v0.15 release notes
  content/en/docs/release-notes/release-notes-0.15.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#196 Add documentation page on the CLI
  .spelling
  content/en/docs/installation/kubernetes.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#202 Update weight of page
  content/en/docs/installation/upgrading/upgrading-0.14-0.15.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#201 Fix invalid resource spec
  content/en/docs/release-notes/release-notes-0.15.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#207 Update install guide to mention installCRDs option
  .spelling
  content/en/docs/installation/kubernetes.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#208 Add note about installCRDs to release notes
  content/en/docs/release-notes/release-notes-0.15.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#206 Merge changes from master into release-next
  .spelling
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/acme-dns.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/uninstall/kubernetes.md
  content/en/docs/installation/upgrading/upgrading-0.13-0.14.md
  package-lock.json
  package.json
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XXL

#209 Roll over version numbers for v0.16
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#210 Merge v0.15 release changes back into master
  .spelling
  config/_default/params.toml
  content/en/.gitignore
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-0.14-0.15.md
  content/en/docs/release-notes/release-notes-0.15.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/kubectl-plugin.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/L

#211 Update upgrade notes to mention '00-crds.yaml' file
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-0.14-0.15.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#214 Correct kubectl-cert-manager URL
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#215 Add Jetstack logo in footer
  assets/icons/jetstack.svg
  assets/scss/_footer.scss
  assets/scss/_search.scss
  assets/scss/main.scss
  content/en/docs/aboutjetstack/_index.md
  layouts/partials/footer.html
Labels: approved, dco-signoff: yes, lgtm, size/L

#216 corrects markdown link parentheses
  content/en/docs/configuration/ca.md
  content/en/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#185 docs(route53): Adding EKS IRSA method
  content/en/docs/configuration/acme/dns01/route53.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#221 Fix GKE RBAC note in installation instructions.
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#218 Updated GoogleDNS docs to describe how to run cert-manager under leas…
  content/en/docs/configuration/acme/dns01/google.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#224 Fixing documentation issue discovered during nginx walkthrough
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#225 update ingress.md
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#230 Add webhook for dnsimple
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#231 Change versions to v0.15.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S
