Repository cert-manager/website, pull requests merged in 2021-04, with the labels that each got.

#491 Make sure all intended headings have anchors
  content/en/docs/installation/kubernetes.md
  content/en/docs/release-notes/release-notes-0.14.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#488 SelfSigned Doc Changes
  _redirects
  content/en/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#498 Add tip using Bazel with corporate/custom CA
  content/en/docs/contributing/building.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#500 Update _index.md
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#489 Update ingress.md
  content/en/docs/usage/ingress.md
Labels: dco-signoff: no, ok-to-test, size/XS

#504 Update release-next
  .spelling
  CONTRIBUTING.md
  OWNERS
  README.md
  _redirects
  assets/icons/logo.svg
  config/_default/params.toml
  content/en/_index.html
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/rfc2136.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/contributing/building.md
  content/en/docs/contributing/external-issuers.md
  content/en/docs/contributing/release-process.md
  content/en/docs/faq/_index.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-0.13.md
  content/en/docs/release-notes/release-notes-0.14.md
  content/en/docs/release-notes/release-notes-0.15.md
  content/en/docs/release-notes/release-notes-0.16.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/release-notes/release-notes-1.2.md
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/en/docs/tutorials/acme/example/ingress-tls.yaml
  content/en/docs/tutorials/acme/example/ingress.yaml
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/_index.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/ingress.md
  content/en/docs/usage/kubectl-plugin.md
  layouts/partials/footer.html
  static/png/cncf.png
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XL

#503 Document the transition to Venafi Cloud OutagePREDICT
  content/en/docs/configuration/venafi.md
  content/en/docs/installation/upgrading/upgrading-1.2-1.3.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.3.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#496 Edits after 1.3.0 alpha.1
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#509 Bump versions
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#506 1.3 release notes
  .spelling
  content/en/docs/release-notes/release-notes-1.3.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#514 [release-1.2] Fix link check lint
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#513 Roll versions forward for 1.3 release
  .spelling
  config/_default/params.toml
  content/en/docs/configuration/venafi.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.2-1.3.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.3.md
  content/en/docs/usage/kubectl-plugin.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/L

#512 Merge v1.3 docs into master
  .spelling
  content/en/docs/configuration/venafi.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.2-1.3.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.3.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, do-not-merge/hold, size/L

#473 Updates CR concept docs with UserInfo fields and fields being immutable
  .spelling
  content/en/docs/concepts/certificaterequest.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#516 Make the 1.3 release-note wording slightly better.
  content/en/docs/release-notes/release-notes-1.3.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#502 Adds approved and denied condition docs
  .spelling
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/configuration/external.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#517 Update the release-1.2 docs
  .spelling
  CONTRIBUTING.md
  OWNERS
  README.md
  _redirects
  config/_default/params.toml
  content/en/_index.html
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/project-maturity.md
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/acme/dns01/rfc2136.md
  content/en/docs/configuration/selfsigned.md
  content/en/docs/contributing/building.md
  content/en/docs/contributing/external-issuers.md
  content/en/docs/contributing/release-process.md
  content/en/docs/faq/_index.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/release-notes/release-notes-0.13.md
  content/en/docs/release-notes/release-notes-0.14.md
  content/en/docs/release-notes/release-notes-0.15.md
  content/en/docs/release-notes/release-notes-0.16.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/en/docs/tutorials/acme/example/ingress-tls.yaml
  content/en/docs/tutorials/acme/example/ingress.yaml
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/_index.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/ingress.md
  content/en/docs/usage/kubectl-plugin.md
  layouts/partials/footer.html
  static/png/cncf.png
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XL

#515 Adds note to external issuer contributions to wait for approval
  .spelling
  content/en/docs/contributing/external-issuers.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#505 add SECURITY.md pointing at main cert-manager repo
  SECURITY.md
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/security.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#520 Release process: RELEASE_NAME is polluting the shell, Helm might be picking it up
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#523 Add style guide
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/coding-conventions.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#526 Coding-conventions: let's settle on the US spelling
  content/en/docs/contributing/coding-conventions.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#524 azuredns: detail how to configure the azureDNS issuer
  content/en/docs/configuration/acme/dns01/azuredns.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#527 Fix typo on the cert flow explanation
  content/en/docs/faq/troubleshooting.md
Labels: approved, dco-signoff: no, dco-signoff: yes, lgtm, ok-to-test, size/XS

#525 Update prometheus-metrics.md
  content/en/docs/usage/prometheus-metrics.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#530 Bump version 1.3.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#531 Update backup instructions
  .spelling
  content/en/docs/tutorials/backup.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#534 Moves the small step external issuer as an approval honoured issuer
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#499 Add note using CA issuer as intermediate
  content/en/docs/configuration/ca.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#536 Fix grammar
  content/en/docs/configuration/vault.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#541 Remove old TODO message
  content/en/docs/tutorials/acme/dns-validation.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
