Repository cert-manager/website, pull requests merged in 2021-07, with the labels that each got.

#620 Change language and weighting in various index pages
  content/en/docs/aboutjetstack/_index.md
  content/en/docs/concepts/_index.md
  content/en/docs/configuration/_index.md
  content/en/docs/installation/_index.md
  content/en/docs/tutorials/_index.md
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#641 Adds a release note for upgrading legacy CRDs
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#582 Add the "life of a certificate" diagram
  content/en/docs/concepts/certificate.md
  content/en/images/letsencrypt-flow-cert-manager.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#639 Fix kuard example WSOD
  content/en/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/en/docs/tutorials/acme/example/ingress-tls.yaml
  content/en/docs/tutorials/acme/example/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#644 Add BizflyCloud Cert-manager webhook
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#636 Updates release notes
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#649 Updates go version to 1.16.6
  .go-version
Labels: approved, dco-signoff: yes, lgtm, size/XS

#648 Update text in e2e test docs
  .spelling
  content/en/docs/contributing/e2e.md
Labels: approved, dco-signoff: yes, do-not-merge/hold, kind/documentation, lgtm, size/L

#651 Minor notes found when doing release process for the first time
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#646 Release-process: I did not know how to update the release branch
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#647 restructured install documentation
  .spelling
  _redirects
  content/en/docs/concepts/webhook.md
  content/en/docs/configuration/acme/dns01/google.md
  content/en/docs/installation/_index.md
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/installation/other-tools.md
  content/en/docs/installation/uninstall.md
  content/en/docs/installation/uninstall/kubernetes.md
  content/en/docs/installation/uninstall/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.3-1.4.md
  content/en/docs/installation/verify.md
  content/en/docs/release-notes/release-notes-1.4.md
  content/en/docs/tutorials/venafi/venafi.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XXL

#657 Update certificate concepts doc, clarifying lack of root in tls.crt
  content/en/docs/concepts/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#653 DCO Sign Off: Fix broken link
  content/en/docs/contributing/sign-off.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#658 Fix typo in supported releases
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#656 Add 'kubectl cert-manager check api' docs
  content/en/docs/installation/verify.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#578 A note of caution about the use of ca.crt
  content/en/docs/concepts/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#521 Talk about key rotation downtime and "rotationPolicy: Always"
  .spelling
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#663 Update artifacthub link
  content/en/docs/installation/upgrading/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#664 Update supported releases
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#558 While restoring a backup, the uid and resourceVersion should be ignored
  content/en/docs/tutorials/backup.md
Labels: approved, dco-signoff: yes, lgtm, size/S
