Repository cert-manager/website, pull requests merged in 2021-02, with the labels that each got.

#420 Move externalloadbalancer to acme/http01/
  _redirects
  content/en/docs/configuration/acme/http01/externalloadbalancer.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#418 Fix code block formatting
  content/en/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#421 Nginx ingress chart name is now ingress-nginx
  content/en/docs/tutorials/acme/ingress.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#411 Fixes a broken to link to Kubernetes docs
  content/en/docs/concepts/webhook.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#417 add -w0 to base64 command to get a singel line
  content/en/docs/configuration/ca.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, priority/backlog, size/XS

#398 Add link to freeipa-issuer
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#419 Mention test-grid and the alert google group
  content/en/docs/contributing/e2e.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#396 Add deprecation notices for old k8s
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#365 Add Feature Policy
  .spelling
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/policy.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#430 Revert "Add deprecation notices for old k8s"
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#424 Add notes I took during the 1.2-alpha.2 release party
  .spelling
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#435 Add notes from the 1.2 release party (the real 1.2 release)
  .spelling
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#434 Release 1.2
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#437 Updates installation guide to use 1.2
  content/en/docs/concepts/project-maturity.md
  content/en/docs/contributing/crds.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#440 Ff release next
  .spelling
  content/en/docs/concepts/project-maturity.md
  content/en/docs/contributing/crds.md
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#439 Update website default version to v1.2
  config/_default/params.toml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#438 Ff release 1.2
  .spelling
  content/en/docs/concepts/project-maturity.md
  content/en/docs/contributing/crds.md
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#441 Updates v1.1.0 references to v1.1.1
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/S

#443 Add detailed release notes for 1.2
  .spelling
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#415 Mention cert-manager-verifier in the docs
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#444 [release-1.2] Add detailed release notes for 1.2
  .spelling
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.2.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#445 Update helm install command to create namespace
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#450 Update project-maturity.md
  content/en/docs/concepts/project-maturity.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#449 Update external-issuers.md
  content/en/docs/contributing/external-issuers.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
