Repository cert-manager/website, pull requests merged in 2021-12, with the labels that each got.

#767 venafi: service-generated CSRs must not be locked
  content/en/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#744 Don't show removed API reference docs
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, lgtm, size/M

#774 Update release date (with note) for 1.7
  content/en/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#778 Update supported releases with the agreed-upon timeline for 1.7
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#782 release-process: mention the removal/re-enabling of next periodics
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#783 Change call to action button to be more descriptive
  content/en/_index.html
Labels: approved, size/XS, dco-signoff: yes, lgtm

#768 Bring the release-next docs up to date
  .spelling
  _redirects
  content/en/_index.html
  content/en/docs/configuration/acme/dns01/_index.md
  content/en/docs/configuration/venafi.md
  content/en/docs/contributing/release-process.md
  content/en/docs/faq/kubed.md
  content/en/docs/installation/_index.md
  content/en/docs/installation/code-signing.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/remove-deprecated-apis.md
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/installation/upgrading/upgrading-1.5-1.6.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/release-notes/release-notes-1.6.md
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/acme/dns-validation.md
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/usage/certificate.md
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#784 Bare release notes and upgrade documentation for 1.7
  content/en/docs/installation/upgrading/upgrading-1.6-1.7.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/M

#786 Install 1.7.0-alpha.0
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#785 Update website config for the 1.7 release
  config/_default/params.toml
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm

#787 typo
  content/en/docs/installation/helm.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#789 Update _index.md
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#777 typo
  content/en/docs/usage/ingress.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#775 Fix incorrect indentation in documentation
  content/en/docs/configuration/acme/_index.md
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#757 fix broken links
  content/en/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test
