Repository cert-manager/website, pull requests merged in 2021-08, with the labels that each got.

#661 FAQ Tweaks, Including Root Chain FAQ + Terminology
  content/en/docs/faq/_index.md
  content/en/docs/faq/terminology.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#666 Add a blank release notes and upgrade page for v1.5
  content/en/docs/installation/upgrading/upgrading-1.4-1.5.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.5.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#634 feat: update secretTemplate documentation
  .spelling
  content/en/docs/release-notes/release-notes-1.5.md
  content/en/docs/usage/certificate.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#655 Install add 'kubectl cert-manager x install' documentation
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl-plugin.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/release-notes/release-notes-1.5.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, ok-to-test, size/XL

#667 Updates for Venafi as a Service
  .spelling
  content/en/docs/configuration/venafi.md
  content/en/images/high-level-overview.svg
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL

#668 Merge changes in master branch in to release-next branch
  .spelling
  content/en/docs/concepts/certificate.md
  content/en/docs/configuration/acme/dns01/akamai.md
  content/en/docs/configuration/venafi.md
  content/en/docs/contributing/sign-off.md
  content/en/docs/faq/_index.md
  content/en/docs/faq/terminology.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/_index.md
  content/en/docs/tutorials/backup.md
  content/en/docs/usage/certificate.md
  content/en/images/high-level-overview.svg
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XXL

#640 Document the certificate shim support for Gateways
  .spelling
  content/en/docs/usage/gateway.md
  content/en/docs/usage/ingress.md
  content/en/images/gateway-roles.png
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#674 release notes 1.5: copy over from https://hackmd.io/f3yFZBP3ScO_BsaPn…
  .spelling
  content/en/docs/release-notes/release-notes-1.5.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#625 Document the use of the HTTP01 Gateway API solver
  .gitattributes
  .spelling
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/usage/gateway.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#677 Update Install intructions for 1.5
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#675 Merge release-next into master for the 1.5 release
  .gitattributes
  .spelling
  config/_default/params.toml
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl-plugin.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/upgrading-1.4-1.5.md
  content/en/docs/installation/verify.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.5.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/gateway.md
  content/en/docs/usage/ingress.md
  content/en/docs/usage/kube-csr.md
  content/en/docs/usage/kubectl-plugin.md
  content/en/images/gateway-roles.png
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#673 Fix broken certificaterequest yaml
  content/en/docs/concepts/certificaterequest.md
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#683 Fix k8s versions we test against on master
  content/en/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#685 Remove alex check
  package-lock.json
  package.json
  scripts/verify-lint
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#686 Update plugin download command to always download latest version
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#684 Don't force GOPROXY when generating docs
  scripts/gendocs/generate
Labels: approved, size/XS, dco-signoff: yes, lgtm

#682 adding docs for cloud provider tests
  content/en/docs/contributing/e2e.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#690 Bump helm installed cm version v1.5.0 -> v1.5.3
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#691 Bump version 1.4.0 -> 1.4.4 in installation instructions
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S
