Repository cert-manager/website, pull requests merged in 2021-03, with the labels that each got.

#458 Fix incorrectly documented default duration
  .spelling
  content/en/docs/faq/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#460 Fix the SVG logo file using the source .ai file
  assets/icons/logo.svg
Labels: approved, dco-signoff: yes, lgtm, size/L

#465 docs(installation): fixed link in k8s install guide
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#453 Use the X.509 typography instead of "x509"
  .spelling
  content/en/_index.html
  content/en/docs/concepts/certificate.md
  content/en/docs/concepts/certificaterequest.md
  content/en/docs/concepts/webhook.md
  content/en/docs/release-notes/release-notes-0.13.md
  content/en/docs/release-notes/release-notes-0.15.md
  content/en/docs/release-notes/release-notes-0.16.md
  content/en/docs/release-notes/release-notes-0.5.md
  content/en/docs/release-notes/release-notes-0.6.md
  content/en/docs/release-notes/release-notes-0.7.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#472 Update API version from deprecated ones
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/en/docs/tutorials/acme/example/ingress-tls.yaml
  content/en/docs/tutorials/acme/example/ingress.yaml
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/tutorials/venafi/venafi.md
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#474 docs: add Marcel's cert-manager video to tutorials
  content/en/docs/tutorials/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#476 Fix ingress examples for the new API
  content/en/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/en/docs/tutorials/acme/example/ingress-tls.yaml
  content/en/docs/tutorials/acme/example/ingress.yaml
  content/en/docs/tutorials/venafi/venafi.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#482 Adding new webhook for Loopia
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#483 Add myself to OWNERS
  CONTRIBUTING.md
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#492 Removes duplicated index entry
  content/en/docs/usage/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#487 Release process updates observed during v1.3.0-alpha.0
  .spelling
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#494 Add minimum supported Bazel version
  README.md
  content/en/docs/contributing/building.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#490 Removes a deprecated note
  content/en/docs/installation/openshift.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#407 Update site copyright to CNCF guidelines
  content/en/_index.html
  layouts/partials/footer.html
  static/png/cncf.png
Labels: approved, dco-signoff: yes, lgtm, size/S
