Repository cert-manager/website, pull requests merged in 2021-05, with the labels that each got.

#522 Differentiate the types of releases: initial alpha, subsequent alpha, beta, final and patch releases
  .spelling
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#452 A "supported-releases" page to give a support timeline
  .spelling
  assets/scss/_styles_project.scss
  content/en/docs/contributing/contributing-flow.md
  content/en/docs/contributing/release-process.md
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#560 ExperimentalCertificateControllers=true no longer needed for key rotation
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#566 Presubmits are now tested on Kubernetes 1.21
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#552 Do not specify namespace for DO DNS01 secret
  content/en/docs/configuration/acme/dns01/digitalocean.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#553 Update kubernetes.md: hub.helm.sh -> artifacthub.io
  content/en/docs/installation/kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#535 Broken Create a Personal access token URL
  content/en/docs/configuration/acme/dns01/digitalocean.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#550 Add docs for third party code donations
  .spelling
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/third-party-code-donation.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#563 Remove the now duplicate "project-maturity" page
  _redirects
  content/en/docs/concepts/project-maturity.md
  content/en/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/en/docs/release-notes/release-notes-1.2.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#576 Move origin-ca-issuer into the honoured approved list
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#574 Mention that the acme-dns implementation can only do one challenge per subdomain
  .spelling
  content/en/docs/configuration/acme/dns01/acme-dns.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#564 Detail why we are still supporting Kubernetes 1.16 & document GKE Autopilot incompatibility
  content/en/docs/installation/compatibility.md
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/M
