Repository cert-manager/website, pull requests merged in 2021-11, with the labels that each got.

#741 Update 1.6 release notes for v1.6.1
  content/en/docs/release-notes/release-notes-1.6.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#727 Update kubed sync example and use secret template instead of pre-annotated secret
  .spelling
  content/en/docs/faq/kubed.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#700 DNS01 webhooks : add cert-manager-alidns-webhook
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#743 Add the splat to redirect URL
  _redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#745 Remove references to removed API versions
  content/en/docs/tutorials/acme/ingress.md
  content/en/docs/usage/certificate.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#748 Add temp 302 redirect to all other paths than the root
  _redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#747 adding redirect rules to prevent google links from reaching page not …
  _redirects
  content/en/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/en/docs/release-notes/release-notes-0.11.md
  content/en/docs/release-notes/release-notes-0.9.md
  content/en/docs/tutorials/acme/dns-validation.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#750 Add specific redirect rule for docs subdomain
  _redirects
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#754 Broaden redirect for "latest/tasks" path on old docs site
  _redirects
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#755 Redirect all 404s to the root of the site
  _redirects
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#756 Revert "redirect all 404s to the root of the site"
  _redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm

#759 Reorder some of the language in signature verification docs
  content/en/docs/installation/code-signing.md
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#760 Add link to AWS blog post on tutorials page
  content/en/docs/tutorials/_index.md
Labels: kind/feature, approved, size/XS, dco-signoff: yes, lgtm

#762 Update cloud vendor k8s compat list
  content/en/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, kind/cleanup, lgtm

#763 Update references to 1.6.0 to point to 1.6.1
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/upgrading/remove-deprecated-apis.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S
