Repository cert-manager/website, pull requests merged in 2021-06, with the labels that each got.

#577 improve language describing ingress hosts
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#575 Make warning about clashing ports on AWS more clear
  .spelling
  content/en/docs/installation/compatibility.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#565 Update instructions for merging the Helm chart PR
  .spelling
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#570 Update renewal docs
  .spelling
  content/en/docs/faq/_index.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.4.md
  content/en/docs/usage/certificate.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#580 Stored objects update instructions
  content/en/docs/contributing/crds.md
  content/en/docs/installation/upgrading/remove-deprecated-apis.md
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#586 Add a section about Certificate's renewal time calculation
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#591 Work around spelling exceptions added to release-next
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#593 improve the example in self-signed docs
  content/en/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#595 Adds upgrade for 1.3 -> 1.4 (no special notes)
  content/en/docs/installation/upgrading/upgrading-1.3-1.4.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/XS

#603 Update ca-injector.md
  content/en/docs/concepts/ca-injector.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#587 Certificate signing request ca issuer
  .spelling
  content/en/docs/faq/_index.md
  content/en/docs/usage/kube-csr.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#608 Fixes typo
  content/en/_index.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#598 Update EAB to reflect requirement for the MAC algorithm being removed
  .spelling
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#599 Multiple selector types per block all need to match
  content/en/docs/configuration/acme/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#601 Update supported annotations for ingress-shim Ingress
  content/en/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#605 Write the 1.4 release notes
  .spelling
  content/en/docs/release-notes/release-notes-1.3.md
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/L

#606 Update supported-releases for 1.4
  content/en/docs/installation/supported-releases.md
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, size/M

#611 Roll versions forward for v1.4 release
  config/_default/params.toml
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/usage/kubectl-plugin.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, lgtm, size/S

#610 Merge release-next into master for the 1.4 release
  .spelling
  content/en/docs/contributing/crds.md
  content/en/docs/faq/_index.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/remove-deprecated-apis.md
  content/en/docs/installation/upgrading/upgrading-1.3-1.4.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.3.md
  content/en/docs/release-notes/release-notes-1.4.md
  content/en/docs/usage/certificate.md
  content/en/docs/usage/kube-csr.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#614 fix relative link in 1.4 release notes
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#613 Update some insecure npm dependencies
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#617 Update renewal time docs
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#607 Release-process: mention the code freeze
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#619 Allow custom bind addresses for development servers
  scripts/server
  scripts/server-release
Labels: approved, dco-signoff: yes, lgtm, size/S

#621 upgrade-1.3-1.4 was displayed after upgrade-1.2-1.3
  content/en/docs/installation/upgrading/upgrading-1.3-1.4.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#618 Tweak landing page, main docs page + footer
  assets/scss/main.scss
  content/en/_index.html
  content/en/docs/_index.md
  layouts/partials/footer.html
Labels: approved, dco-signoff: yes, lgtm, size/L

#626 Documentation for the new cert-manager release on OperatorHub
  .spelling
  content/en/docs/installation/kubernetes.md
  content/en/docs/installation/openshift.md
  content/en/docs/installation/upgrading/upgrading-1.3-1.4.md
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#630 Update the link and name of the aws-privateca-issuer
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#546 Update external issuer docs
  .spelling
  content/en/docs/configuration/external.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#631 Adds the correct PR links, fixes a typo
  content/en/docs/release-notes/release-notes-1.4.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#632 Remove lingering refs
  content/en/docs/faq/_index.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#623 Supported-releases: add the supported versions of OpenShift
  .spelling
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/M
