Repository cert-manager/website, pull requests merged in 2022-05, with the labels that each got.

#959 Add public docssearch variables to netlify.toml
  netlify.toml
Labels: approved, size/XS, dco-signoff: yes, lgtm

#960 fix: add deployment url and current url for canoncial links
  lib/currentUrl.js
  netlify.toml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#962 fix: dupe protocol
  lib/currentUrl.js
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#961 Fix Pomerium examples
  content/docs/tutorials/acme/pomerium-ingress.md
  content/next-docs/tutorials/acme/pomerium-ingress.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#963 Opengraph updates
  content/docs/README.md
  content/docs/configuration/external.md
  content/pages/homepage.mdx
  content/pages/support.mdx
  next-seo.config.js
  pages/[...docs].jsx
  public/images/cert-manager-graphic.png
  public/images/cert-manager-logo-icon.svg
  public/images/cloud-native-logo.png
  public/images/gateway-roles.png
  public/images/og.png
  public/images/og1.png
  raw-images/README.md
  raw-images/cert-manager-graphic.svg
  raw-images/cert-manager-og.xcf
Labels: approved, dco-signoff: yes, lgtm, size/L

#965 Use NEXT_PUBLIC_URL to configure the site base URL
  .env
  next-seo.config.js
  next-sitemap.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#927 Update uninstallation instructions
  .spelling
  content/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#967 Revert "use NEXT_PUBLIC_URL to configure the site base URL"
  .env
  next-seo.config.js
  next-sitemap.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#966 fix: new svg for better performance
  content/pages/homepage.mdx
  public/images/cert-manager-graphic.png
  public/images/cert-manager-graphic.svg
  raw-images/cert-manager-graphic.svg
Labels: approved, dco-signoff: yes, lgtm, size/L, needs-ok-to-test

#972 Remove a header which previously had autofilled hugo content
  content/docs/configuration/README.md
  content/next-docs/configuration/README.md
  content/v0.12-docs/configuration/README.md
  content/v0.13-docs/configuration/README.md
  content/v0.14-docs/configuration/README.md
  content/v0.15-docs/configuration/README.md
  content/v0.16-docs/configuration/README.md
  content/v1.0-docs/configuration/README.md
  content/v1.1-docs/configuration/README.md
  content/v1.2-docs/configuration/README.md
  content/v1.3-docs/configuration/README.md
  content/v1.4-docs/configuration/README.md
  content/v1.5-docs/configuration/README.md
  content/v1.6-docs/configuration/README.md
  content/v1.7-docs/configuration/README.md
  content/v1.8-docs/configuration/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#973 Update ingress-class-compatibility.md
  content/docs/installation/upgrading/ingress-class-compatibility.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#976 Various redirects and renames + sitemap fix
  .gitignore
  content/docs/contributing/google-season-of-docs/2022/README.md
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure.md
  content/docs/manifest.json
  content/next-docs/aboutjetstack/README.md
  content/next-docs/manifest.json
  next-sitemap.js
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/M

#977 Allow local debugging of Netlify redirects
  README.md
  public/_redirects
  scripts/server-netlify
Labels: approved, dco-signoff: yes, lgtm, size/L

#978 chore(spelling): accessible
  README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#979 Clarify that google DNS01 requires a public DNS zone
  content/docs/configuration/acme/dns01/google.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#980 Update release date for 1.9
  content/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#710 Added ZeroSSL tutorial
  content/v1.8-docs/tutorials/README.md
  content/v1.8-docs/tutorials/zerossl/zerossl.md
Labels: approved, dco-signoff: yes, lgtm, size/L, ok-to-test

#983 Document how to configure cert-manager via OLM
  .spelling
  content/docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#985 Fix the link to `Upgrading from v1.7 to v1.8` in release notes for `1.8`
  content/docs/release-notes/release-notes-1.8.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#956 add external link to Netcup ACME webhook
  content/v1.7-docs/configuration/acme/dns01/README.md
  content/v1.8-docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#986 Add ncm-issuer to external issuers list
  .spelling
  content/docs/configuration/external.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#990 Update to smaller logo in README
  README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
