Repository cert-manager/website, pull requests merged in 2022-01, with the labels that each got.

#792 Add CFSSL Issuer to the external issuers list
  content/en/docs/configuration/external.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#795 Updates supported releases page
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#764 Pomerium Ingress Tutorial
  .spelling
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/acme/example/pomerium-certificates.yaml
  content/en/docs/tutorials/acme/example/pomerium-production-issuer.yaml
  content/en/docs/tutorials/acme/example/pomerium-staging-issuer.yaml
  content/en/docs/tutorials/acme/example/pomerium-values.yaml
  content/en/docs/tutorials/acme/nginx-ingress.md
  content/en/docs/tutorials/acme/pomerium-ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/L, ok-to-test

#793 Update instructions for upgrading cert-manager resources and CRDs
  .spelling
  content/en/docs/installation/upgrading/remove-deprecated-apis.md
  content/en/docs/usage/cmctl.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#796 Add cert-manager-webhook-linode to webhooks list
  content/en/docs/configuration/acme/dns01/_index.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#794 Update troubleshooting docs
  content/en/docs/faq/acme.md
  content/en/docs/faq/webhook.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#797 Adds section in usage/certificates for additional output formats
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/M

#798 fix arrow character in testing coverage table
  content/en/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#761 Add kubectl plugin Windows installation instructions
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#803 Release notes for 1.7
  .spelling
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#800 generate cli reference docs
  .go-version
  content/en/.gitignore
  content/en/docs/cli/_index.md
  content/en/v0.15-docs/cli/_index.md
  content/en/v0.15-docs/cli/cainjector.md
  content/en/v0.15-docs/cli/cmctl.md
  content/en/v0.15-docs/cli/controller.md
  content/en/v0.16-docs/cli/_index.md
  content/en/v0.16-docs/cli/acmesolver.md
  content/en/v0.16-docs/cli/cainjector.md
  content/en/v0.16-docs/cli/cmctl.md
  content/en/v0.16-docs/cli/controller.md
  content/en/v0.16-docs/cli/webhook.md
  content/en/v1.0-docs/cli/_index.md
  content/en/v1.0-docs/cli/acmesolver.md
  content/en/v1.0-docs/cli/cainjector.md
  content/en/v1.0-docs/cli/cmctl.md
  content/en/v1.0-docs/cli/controller.md
  content/en/v1.0-docs/cli/webhook.md
  content/en/v1.1-docs/cli/_index.md
  content/en/v1.1-docs/cli/acmesolver.md
  content/en/v1.1-docs/cli/cainjector.md
  content/en/v1.1-docs/cli/cmctl.md
  content/en/v1.1-docs/cli/controller.md
  content/en/v1.1-docs/cli/webhook.md
  content/en/v1.2-docs/cli/_index.md
  content/en/v1.2-docs/cli/acmesolver.md
  content/en/v1.2-docs/cli/cainjector.md
  content/en/v1.2-docs/cli/cmctl.md
  content/en/v1.2-docs/cli/controller.md
  content/en/v1.2-docs/cli/webhook.md
  content/en/v1.3-docs/cli/_index.md
  content/en/v1.3-docs/cli/acmesolver.md
  content/en/v1.3-docs/cli/cainjector.md
  content/en/v1.3-docs/cli/cmctl.md
  content/en/v1.3-docs/cli/controller.md
  content/en/v1.3-docs/cli/webhook.md
  content/en/v1.4-docs/cli/_index.md
  content/en/v1.4-docs/cli/acmesolver.md
  content/en/v1.4-docs/cli/cainjector.md
  content/en/v1.4-docs/cli/cmctl.md
  content/en/v1.4-docs/cli/controller.md
  content/en/v1.4-docs/cli/webhook.md
  content/en/v1.5-docs/cli/_index.md
  content/en/v1.5-docs/cli/acmesolver.md
  content/en/v1.5-docs/cli/cainjector.md
  content/en/v1.5-docs/cli/cmctl.md
  content/en/v1.5-docs/cli/controller.md
  content/en/v1.5-docs/cli/webhook.md
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#806 add acme-http01-solver-nameservers flag documentation
  .spelling
  content/en/docs/configuration/acme/http01/_index.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S, ok-to-test

#766 Adds comment to SecretTemplate about feature gate
  content/en/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#810 Pull latest master into release-next branch
  .go-version
  content/en/.gitignore
  content/en/docs/cli/_index.md
  content/en/docs/contributing/release-process.md
  content/en/v0.15-docs/cli/_index.md
  content/en/v0.15-docs/cli/cainjector.md
  content/en/v0.15-docs/cli/cmctl.md
  content/en/v0.15-docs/cli/controller.md
  content/en/v0.16-docs/cli/_index.md
  content/en/v0.16-docs/cli/acmesolver.md
  content/en/v0.16-docs/cli/cainjector.md
  content/en/v0.16-docs/cli/cmctl.md
  content/en/v0.16-docs/cli/controller.md
  content/en/v0.16-docs/cli/webhook.md
  content/en/v1.0-docs/cli/_index.md
  content/en/v1.0-docs/cli/acmesolver.md
  content/en/v1.0-docs/cli/cainjector.md
  content/en/v1.0-docs/cli/cmctl.md
  content/en/v1.0-docs/cli/controller.md
  content/en/v1.0-docs/cli/webhook.md
  content/en/v1.1-docs/cli/_index.md
  content/en/v1.1-docs/cli/acmesolver.md
  content/en/v1.1-docs/cli/cainjector.md
  content/en/v1.1-docs/cli/cmctl.md
  content/en/v1.1-docs/cli/controller.md
  content/en/v1.1-docs/cli/webhook.md
  content/en/v1.2-docs/cli/_index.md
  content/en/v1.2-docs/cli/acmesolver.md
  content/en/v1.2-docs/cli/cainjector.md
  content/en/v1.2-docs/cli/cmctl.md
  content/en/v1.2-docs/cli/controller.md
  content/en/v1.2-docs/cli/webhook.md
  content/en/v1.3-docs/cli/_index.md
  content/en/v1.3-docs/cli/acmesolver.md
  content/en/v1.3-docs/cli/cainjector.md
  content/en/v1.3-docs/cli/cmctl.md
  content/en/v1.3-docs/cli/controller.md
  content/en/v1.3-docs/cli/webhook.md
  content/en/v1.4-docs/cli/_index.md
  content/en/v1.4-docs/cli/acmesolver.md
  content/en/v1.4-docs/cli/cainjector.md
  content/en/v1.4-docs/cli/cmctl.md
  content/en/v1.4-docs/cli/controller.md
  content/en/v1.4-docs/cli/webhook.md
  content/en/v1.5-docs/cli/_index.md
  content/en/v1.5-docs/cli/acmesolver.md
  content/en/v1.5-docs/cli/cainjector.md
  content/en/v1.5-docs/cli/cmctl.md
  content/en/v1.5-docs/cli/controller.md
  content/en/v1.5-docs/cli/webhook.md
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, size/XXL, cherry-pick-approved, lgtm

#813 Update Install and upgrade instructions for 1.7
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/upgrading-1.6-1.7.md
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm

#812 Add notes on Ingress Class compatibility for 1.5-1.7
  .spelling
  content/en/docs/installation/upgrading/ingress-class-compatibility.md
  content/en/docs/installation/upgrading/upgrading-1.4-1.5.md
  content/en/docs/installation/upgrading/upgrading-1.5-1.6.md
  content/en/docs/installation/upgrading/upgrading-1.6-1.7.md
  content/en/docs/release-notes/release-notes-1.5.md
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#815 Update release-notes with latest output of the release-notes tool
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, size/XS, dco-signoff: yes, cherry-pick-approved, lgtm

#811 fix CLI reference generation for current and next versions
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, lgtm, size/M

#817 Update the CLI docs and doc scripts for the 1.7 release
  content/en/v1.6-docs/cli/acmesolver.md
  content/en/v1.6-docs/cli/cainjector.md
  content/en/v1.6-docs/cli/cmctl.md
  content/en/v1.6-docs/cli/controller.md
  content/en/v1.6-docs/cli/webhook.md
  content/en/v1.7-docs/cli/_index.md
  content/en/v1.7-docs/cli/acmesolver.md
  content/en/v1.7-docs/cli/cainjector.md
  content/en/v1.7-docs/cli/cmctl.md
  content/en/v1.7-docs/cli/controller.md
  content/en/v1.7-docs/cli/webhook.md
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#814 Merge the 1.7 documentation changes
  .spelling
  config/_default/params.toml
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/installation/supported-releases.md
  content/en/docs/installation/upgrading/ingress-class-compatibility.md
  content/en/docs/installation/upgrading/upgrading-1.4-1.5.md
  content/en/docs/installation/upgrading/upgrading-1.5-1.6.md
  content/en/docs/installation/upgrading/upgrading-1.6-1.7.md
  content/en/docs/release-notes/_index.md
  content/en/docs/release-notes/release-notes-1.5.md
  content/en/docs/release-notes/release-notes-1.7.md
  content/en/docs/usage/certificate.md
  content/en/v1.6-docs/cli/acmesolver.md
  content/en/v1.6-docs/cli/cainjector.md
  content/en/v1.6-docs/cli/cmctl.md
  content/en/v1.6-docs/cli/controller.md
  content/en/v1.6-docs/cli/webhook.md
  content/en/v1.7-docs/cli/_index.md
  content/en/v1.7-docs/cli/acmesolver.md
  content/en/v1.7-docs/cli/cainjector.md
  content/en/v1.7-docs/cli/cmctl.md
  content/en/v1.7-docs/cli/controller.md
  content/en/v1.7-docs/cli/webhook.md
  scripts/gendocs/generate
  scripts/update-content
  scripts/verify-lint
Labels: approved, dco-signoff: yes, size/XL, lgtm

#818 Be more specific about about the versions affected by HTTP-01 regress…
  .spelling
  content/en/docs/installation/upgrading/ingress-class-compatibility.md
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#819 add jahrlin to OWNERS
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#807 fix installation package for MacOS
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#823 Use v1.5.5 in the installation documentation for 1.5
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm

#822 Use v1.6.2 in the installation documentation for 1.6
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/usage/cmctl.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#824 Fix incorrect 1.6 patch numbers
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#827 Improve the documentation of how to change the release-next periodic tests
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#829 add old API references to git index and clean up the generate script
  content/en/.gitignore
  content/en/v0.12-docs/reference/api-docs.md
  content/en/v0.13-docs/reference/api-docs.md
  content/en/v0.14-docs/reference/api-docs.md
  content/en/v0.15-docs/reference/api-docs.md
  content/en/v0.16-docs/reference/api-docs.md
  content/en/v1.0-docs/reference/api-docs.md
  content/en/v1.1-docs/reference/api-docs.md
  content/en/v1.2-docs/reference/api-docs.md
  content/en/v1.3-docs/reference/api-docs.md
  content/en/v1.4-docs/reference/api-docs.md
  content/en/v1.5-docs/reference/api-docs.md
  content/en/v1.6-docs/cli/_index.md
  content/en/v1.6-docs/reference/api-docs.md
  scripts/gendocs/generate
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#828 Add @wallrj to OWNERS
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm
