Repository cert-manager/website, pull requests merged in 2022-04, with the labels that each got.

#895 Change stage -> makestage for a release
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#892 Update to current Venafi branding
  content/en/images/high-level-overview.svg
Labels: approved, dco-signoff: yes, size/XL, lgtm, ok-to-test

#887 fix mistaken reflector annotation
  content/en/docs/faq/sync-secrets.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#865 Add a paragraph about releasing OLM packages
  content/en/docs/contributing/release-process.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#897 gateway-api: update the docs for v1alpha2
  .spelling
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/installation/upgrading/upgrading-1.7-1.8.md
  content/en/docs/usage/gateway.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#901 gatewayapi acme: fix upgrading-1.7-1.8 link
  content/en/docs/configuration/acme/http01/_index.md
  content/en/docs/usage/gateway.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#902 Fully update supported releases page after 1.8 release
  content/en/docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#903 Don't run build script for old crd docs by default
  scripts/gendocs/generate
  scripts/gendocs/generate-old-import-path-docs
Labels: approved, dco-signoff: yes, lgtm, size/S

#864 Add kubernetes-replicator to FAQ/Sync Secrets
  .spelling
  content/docs/faq/sync-secrets.md
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#910 Various post-release updates to scripts
  README.md
  _redirects
  components/Footer.jsx
  scripts/_verify
  scripts/bin/htmltest
  scripts/bin/hugo
  scripts/bin/lib.sh
  scripts/bin/multiversion
  scripts/build
  scripts/build-release
  scripts/gendocs/generate-new-import-path-docs
  scripts/gendocs/generate-old-import-path-docs
  scripts/index
  scripts/server
  scripts/server-release
  scripts/update-node_modules
  scripts/verify
  scripts/verify-lint
  scripts/verify-release
Labels: approved, dco-signoff: yes, size/XL, lgtm

#912 Cleanup old files post-refresh
  content/docs/reference/.gitignore
  content/images/gateway-roles.png
  content/images/google-season-of-docs-2022-improve-navigation-and-structure.png
  content/images/high-level-overview.svg
  content/images/letsencrypt-flow-cert-manager.png
  content/images/search-by-algolia-light-background.svg
  content/next-docs/reference/.gitignore
Labels: approved, dco-signoff: yes, size/XL, lgtm

#914 Fix links to slack channels
  content/docs/contributing/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#915 fix: footer bg
  components/Footer.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#919 gsod2022: add a title, and tell that we were accepted
  .spelling
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
Labels: approved, dco-signoff: yes, size/S

#916 Various updates to nginx ingress tutorial
  content/docs/installation/README.md
  content/docs/installation/cmctl.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl-plugin.md
  content/docs/installation/kubectl.md
  content/docs/tutorials/acme/nginx-ingress.md
  content/next-docs/tutorials/acme/nginx-ingress.md
  content/v1.7-docs/tutorials/acme/nginx-ingress.md
  content/v1.8-docs/tutorials/acme/nginx-ingress.md
Labels: approved, dco-signoff: yes, size/XL, lgtm

#925 Changed Github org from jetstack to cert-manager
  SECURITY.md
  content/docs/configuration/acme/dns01/acme-dns.md
  content/docs/configuration/selfsigned.md
  content/docs/contributing/building.md
  content/docs/contributing/coding-conventions.md
  content/docs/contributing/contributing-flow.md
  content/docs/contributing/dns-providers.md
  content/docs/contributing/e2e.md
  content/docs/contributing/release-process.md
  content/docs/contributing/security.md
  content/docs/contributing/third-party-code-donation.md
  content/docs/faq/README.md
  content/docs/installation/compatibility.md
  content/docs/usage/certificate.md
  content/docs/usage/cmctl.md
  content/docs/usage/csi.md
  content/docs/usage/kubectl-plugin.md
  content/docs/usage/prometheus-metrics.md
  content/pages/homepage.mdx
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#924 Correct "cloud native" capitalisation
  content/pages/homepage.mdx
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#920 Update uninstall documentation
  .spelling
  content/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#918 fix: footer bg and margins
  components/Footer.jsx
  pages/[...docs].jsx
  pages/support.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#926 Remove aboutjetstack from the docs section
  content/docs/aboutjetstack/README.md
  content/docs/manifest.json
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/M

#928 gsod: mention the timeline for applying
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#933 fix(docs): add h1 header
  pages/[...docs].jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#935 add NEXT_PUBLIC_ENABLE_ANALYTICS envvar
  netlify.toml
Labels: approved, size/XS, dco-signoff: yes, lgtm

#932 Improve upgrade instructions
  content/docs/installation/upgrading/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#937 add info on GKE Autopilot regarding kube-system namespace
  content/docs/installation/compatibility.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#940 Update venafi.md
  content/docs/configuration/venafi.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#941 GSoD Tweaks
  config/_default/params.toml
  content/docs/contributing/README.md
  content/docs/contributing/google-season-of-docs/2022/README.md
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/README.md
  content/docs/contributing/google-season-of-docs/README.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#939 add logo to harmonize with other org projects
  README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#947 Fix dir structure and infinite redirect
  content/docs/contributing/README.md
  content/docs/contributing/google-season-of-docs/2022/README.md
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure.md
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#949 Revert moving gsod proposal since it seems to break next.js
  content/docs/contributing/google-season-of-docs/2022/README.md
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/index.md
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#951 fix: relative links and trailing slashes
  package-lock.json
  package.json
  pages/[...docs].jsx
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#950 Document how to work on the site a little better
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#943 Contributor area: Improve readme + feature policy
  content/docs/contributing/README.md
  content/docs/contributing/policy.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#954 Fix URL in OG img
  next-seo.config.js
Labels: approved, size/XS, dco-signoff: yes, lgtm

#681 cloudflare: don't configure email with API Tokens
  content/docs/configuration/acme/dns01/cloudflare.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test
