Repository cert-manager/website, pull requests merged in 2022-02, with the labels that each got.

#831 Add a note about updating the krew index after a release
  content/en/docs/contributing/release-process.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#835 Recommends usage of cert-manager/trust for selfsigned certificates
  content/en/docs/configuration/selfsigned.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#830 release-process: disambiguate the example 3 "final release"
  content/en/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#833 Add note about cert-manager's import path
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/importing.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#826 Add the missing entries to the release notes 1.5 and 1.6
  .spelling
  content/en/docs/release-notes/release-notes-1.5.md
  content/en/docs/release-notes/release-notes-1.6.md
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#832 Fix broken HTML in API docs; use latest upstream templates for CRD docs
  scripts/gendocs/generate
  scripts/gendocs/templates/members.tpl
  scripts/gendocs/templates/pkg.tpl
  scripts/gendocs/templates/type.tpl
Labels: approved, dco-signoff: yes, lgtm, size/M

#837 Release notes and installation links for for v1.7.1
  .spelling
  content/en/docs/installation/_index.md
  content/en/docs/installation/helm.md
  content/en/docs/installation/kubectl.md
  content/en/docs/installation/operator-lifecycle-manager.md
  content/en/docs/installation/upgrading/ingress-class-compatibility.md
  content/en/docs/release-notes/release-notes-1.7.md
  content/en/docs/usage/cmctl.md
  content/en/docs/usage/kubectl-plugin.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#840 Add v1.5.5 release-notes
  content/en/docs/release-notes/release-notes-1.5.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#846 Ssa installation warning
  .spelling
  content/en/docs/release-notes/release-notes-1.7.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#848 Add redirects for "project" documentation
  _redirects
Labels: approved, dco-signoff: yes, lgtm, size/M

#855 change header on api-docs to match other files
  content/en/v0.12-docs/reference/api-docs.md
  content/en/v0.13-docs/reference/api-docs.md
  content/en/v0.14-docs/reference/api-docs.md
  content/en/v0.15-docs/reference/api-docs.md
  content/en/v0.16-docs/reference/api-docs.md
  content/en/v1.0-docs/reference/api-docs.md
  content/en/v1.1-docs/reference/api-docs.md
  content/en/v1.2-docs/reference/api-docs.md
  content/en/v1.3-docs/reference/api-docs.md
  content/en/v1.4-docs/reference/api-docs.md
  content/en/v1.5-docs/reference/api-docs.md
  content/en/v1.6-docs/reference/api-docs.md
  content/en/v1.7-docs/reference/api-docs.md
  scripts/gendocs/templates/pkg.tpl
Labels: approved, dco-signoff: yes, lgtm, size/L

#856 Remove a few broken tags which were introduced by mistake
  content/en/docs/contributing/release-process.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
