Repository cert-manager/website, pull requests merged in 2022-10, with the labels that each got.

#1086 update release-notes version to an M1-compatible version
  content/docs/contributing/release-process.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1087 Update release-process.md
  .spelling
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1085 content/projects/csi-driver: Fix PKCS12 attribute keys to correct strings
  content/docs/projects/csi-driver.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1092 add upgrade to 1.10 docs
  content/docs/installation/upgrading/upgrading-1.9-1.10.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#1096 Adds a missing path to 1.10 release notes
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm
