Repository cert-manager/website, pull requests merged in 2022-12, with the labels that each got.

#1124 Fixes typo in webhook troubleshooting
  content/docs/troubleshooting/webhook.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#1110 Rename trust to trust-manager in projects list
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1123 Adds documentation for Gateway API cross-namespace secret refs
  content/docs/usage/gateway.md
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#1126 Specify that the ingress-shim will be created in Ingresses' namespace
  content/docs/usage/ingress.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1131 Update supported releases with latest data
  content/docs/installation/supported-releases.md
  content/next-docs/installation/supported-releases.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1133 Various updates + tweaks
  components/docs/VersionSelect.jsx
  content/docs/installation/supported-releases.md
  content/docs/release-notes/release-notes-0.1.md
  content/next-docs/configuration/acme/README.md
  content/next-docs/installation/supported-releases.md
  content/next-docs/manifest.json
  content/next-docs/release-notes/release-notes-0.1.md
  content/next-docs/release-notes/release-notes-1.10.md
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm, size/L
