Repository cert-manager/website, pull requests merged in 2023-10, with the labels that each got.

#1312 Fix sidemenu collapse
  components/docs/Sidebar/Dropdown.jsx
  components/docs/Sidebar/ListItems.jsx
  components/docs/Sidebar/SidebarLink.jsx
  components/docs/Sidebar/index.jsx
  components/docs/VersionSelect.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1313 Fix broken approver-policy link (google)
  public/_redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1314 Mobile Menu: Partially revert #1312
  components/docs/Sidebar/Dropdown.jsx
  components/docs/Sidebar/ListItems.jsx
  components/docs/Sidebar/SidebarLink.jsx
  components/docs/Sidebar/index.jsx
  components/docs/VersionSelect.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1318 Update support page: replace Jetstack with Venafi
  content/pages/support.mdx
  pages/support.jsx
  public/images/venafi-hero.png
  public/images/venafi-tls-protect-for-kubernetes.svg
Labels: approved, dco-signoff: yes, lgtm, size/M

#1316 Update CLI flag documentation
  content/docs/cli/acmesolver.md
  content/docs/cli/cainjector.md
  content/docs/cli/cmctl.md
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1319 Only include latest version of docs in sitemap
  next-sitemap.config.js
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1315 Move copy icon to fix mobile view
  styles/docs.scss
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1323 update twitter icon to x [Fixes #1321]
  components/Icon.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1311 Cleanup installation section
  .spelling
  content/docs/concepts/webhook.md
  content/docs/contributing/api-compatibility.md
  content/docs/contributing/crds.md
  content/docs/contributing/featuregates.md
  content/docs/installation/configuring-components.md
  content/docs/installation/featureflags.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/other-tools.md
  content/docs/installation/reinstall.md
  content/docs/installation/uninstall.md
  content/docs/installation/upgrade.md
  content/docs/installation/verify.md
  content/docs/manifest.json
  content/docs/reference/cmctl.md
  public/_redirects
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1291 Reorganise the usage section & move missing topics to this section
  .spelling
  content/docs/concepts/acme-orders-challenges.md
  content/docs/contributing/external-issuers.md
  content/docs/manifest.json
  content/docs/policy/approval/README.md
  content/docs/policy/approval/approver-policy/README.md
  content/docs/reference/cmctl.md
  content/docs/usage/certificate.md
  content/docs/usage/certificaterequest.md
  content/docs/usage/csi-driver-spiffe.md
  content/docs/usage/csi-driver.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
  content/docs/usage/kube-csr.md
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/M

#1303 Add command-issuer to external issuers list
  .spelling
  content/docs/configuration/external.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1276 Release-process: sed command not compatible with BSD sed and other improvements
  .spelling
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1326 Update Google DNS doc in case custom role is used
  content/docs/configuration/acme/dns01/google.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1289 Add diagrams to explain all the "requesting certificates" flows
  content/docs/usage/certificate.md
  content/docs/usage/certificaterequest.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
  content/docs/usage/kube-csr.md
  public/images/request-certificate-debug/certificate-flow.drawio
  public/images/request-certificate-debug/certificate-flow.svg
  public/images/request-certificate-debug/certificate-request-flow.drawio
  public/images/request-certificate-debug/certificate-request-flow.svg
  public/images/request-certificate-debug/certificate-signing-request-flow.drawio
  public/images/request-certificate-debug/certificate-signing-request-flow.svg
  public/images/request-certificate-debug/csi-driver-flow.drawio
  public/images/request-certificate-debug/csi-driver-spiffe-flow.drawio
  public/images/request-certificate-debug/gateway-shim-flow.drawio
  public/images/request-certificate-debug/gateway-shim-flow.svg
  public/images/request-certificate-debug/ingress-shim-flow.drawio
  public/images/request-certificate-debug/ingress-shim-flow.svg
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1328 fix: Docs needed Camel case feature gate names
  content/docs/installation/configuring-components.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1332 Add redirect rules for broken links
  content/docs/installation/upgrade.md
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/S

#1333 Fix title casing in sidebar
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1336 Add release notes for v1.13.2
  .spelling
  content/docs/releases/release-notes/release-notes-1.13.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1335 Update documentation to point to latest patch version
  content/docs/cli/controller.md
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/v1.12-docs/installation/README.md
  content/v1.12-docs/installation/code-signing.md
  content/v1.12-docs/installation/helm.md
  content/v1.12-docs/installation/kubectl.md
  content/v1.12-docs/installation/operator-lifecycle-manager.md
  content/v1.13-docs/installation/README.md
  content/v1.13-docs/installation/code-signing.md
  content/v1.13-docs/installation/helm.md
  content/v1.13-docs/installation/kubectl.md
  content/v1.13-docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/M
