Repository cert-manager/website, pull requests merged in 2023-02, with the labels that each got.

#1160 Wide-ranging updates to trust-manager docs for v0.4.0
  .spelling
  content/docs/projects/README.md
  content/docs/projects/trust-manager/README.md
  content/docs/projects/trust-manager/api-reference.md
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L

#1176 Update homepage numbers ⭐
  content/pages/homepage.mdx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1175 Run more checks in GitHub actions and simplify build scripts
  .github/workflows/check.yaml
  README.md
  package-lock.json
  package.json
  scripts/_verify
Labels: approved, dco-signoff: yes, lgtm, size/L

#1177 Remove unused verify-release script
  README.md
  scripts/_verify
  scripts/verify
  scripts/verify-release
Labels: approved, dco-signoff: yes, lgtm, size/M

#1178 Remove unused npm scripts
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1180 Update release process after releasing v1.12.0-alpha.0
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1181 CSS: smaller font for code blocks, 1rem for normal font
  styles/docs.scss
Labels: approved, dco-signoff: yes, lgtm, size/S

#1179 Only generate API and CLI docs on release
  README.md
  content/docs/contributing/release-process.md
  package-lock.json
  package.json
  scripts/build
  scripts/build-release
Labels: approved, dco-signoff: yes, lgtm, size/M

#1184 add more docs on release branches
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1185 Add link to ACME DNS01 webhook for PowerDNS
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1187 Remove p-521 reference, reword list
  content/docs/projects/csi-driver-spiffe.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#992 Initial feature gate documentation
  content/docs/contributing/featuregates.md
  content/docs/installation/featureflags.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, priority/important-soon, size/L

#1188 Updates 1.12 expected release date
  content/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1191 Updates uninstall doc with backup and restore guide link
  content/docs/installation/uninstall.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1190 Helm install: add hint for installCRDs in both cases
  content/docs/installation/helm.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
