Repository cert-manager/website, pull requests merged in 2023-11, with the labels that each got.

#1249 Correct `kubectl operator install` for latest version of operator-sdk
  content/docs/installation/operator-lifecycle-manager.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1327 Reorganise 'Certificate resource' page
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1329 Add overview diagrams for "Requesting Certificates" section
  content/docs/usage/README.md
  content/docs/usage/certificate.md
  content/docs/usage/certificaterequest.md
  content/docs/usage/csi.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
  content/docs/usage/istio-csr.md
  content/docs/usage/kube-csr.md
  public/images/request-certificate-overview/request-certificate-cert.svg
  public/images/request-certificate-overview/request-certificate-cr.svg
  public/images/request-certificate-overview/request-certificate-csi.svg
  public/images/request-certificate-overview/request-certificate-csr.svg
  public/images/request-certificate-overview/request-certificate-gateway.svg
  public/images/request-certificate-overview/request-certificate-ingress.svg
  public/images/request-certificate-overview/request-certificate-mesh.svg
  public/images/request-certificate-overview/request-certificate.drawio
  public/images/request-certificate-overview/request-certificate.svg
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1338 Explain how to install cert-manager using Flux
  content/docs/installation/README.md
  content/docs/installation/continuous-deployment-and-gitops.md
  content/docs/installation/helm.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#1337 Update README.md to reflect that the trust namespace is only for secrets
  content/docs/trust/trust-manager/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1339 Fix broken link
  content/docs/usage/README.md
  content/v1.0-docs/usage/README.md
  content/v1.1-docs/usage/README.md
  content/v1.10-docs/usage/README.md
  content/v1.11-docs/usage/README.md
  content/v1.12-docs/usage/README.md
  content/v1.13-docs/usage/README.md
  content/v1.2-docs/usage/README.md
  content/v1.3-docs/usage/README.md
  content/v1.4-docs/usage/README.md
  content/v1.5-docs/usage/README.md
  content/v1.6-docs/usage/README.md
  content/v1.7-docs/usage/README.md
  content/v1.8-docs/usage/README.md
  content/v1.9-docs/usage/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1340 Clarify that it is the webhook, not the CA Injector, which creates the secret with the webhook's root CA certificate
  content/docs/concepts/webhook.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1341 Bump numbers on homepage
  content/pages/homepage.mdx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1342 docs: Small typo on best practice: is should have been us
  content/docs/installation/best-practice.md
  content/v1.13-docs/installation/best-practice.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1343 Link to the official Flux example repo and remove unnecessary --crds flags from example
  content/docs/installation/continuous-deployment-and-gitops.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1345 Added horizon-issuer as an external issuer
  content/docs/configuration/external.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1344 Network Policy Recommendations
  content/docs/installation/best-practice.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1346 Make Peter Fiddes (@hawksight) a reviewer
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1348 Add v1.13 upgrade note saying you should upgrade to v1.12 first
  content/docs/releases/upgrading/upgrading-1.12-1.13.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1324 Replace external issuers page with list of ALL issuers
  .spelling
  content/docs/configuration/external.md
  content/docs/configuration/issuers.md
  content/docs/contributing/external-issuers.md
  content/docs/manifest.json
  content/docs/policy/approval/approver-policy/README.md
  public/_redirects
  styles/global.scss
Labels: approved, dco-signoff: yes, lgtm, size/L

#1352 Removing the 'concepts' > 'Certificate' page
  content/docs/concepts/acme-orders-challenges.md
  content/docs/concepts/certificate.md
  content/docs/manifest.json
  content/docs/tutorials/acme/http-validation.md
  content/docs/tutorials/acme/nginx-ingress.md
  content/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/README.md
  content/docs/usage/README.md
  content/docs/usage/certificate.md
  content/docs/usage/certificaterequest.md
  content/docs/usage/ingress.md
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/L

#1351 Add/update docs for new trust-manager features
  .spelling
  content/docs/trust/trust-manager/README.md
  content/docs/trust/trust-manager/api-reference.md
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L
