Repository cert-manager/website, pull requests merged in 2023-01, with the labels that each got.

#1134 Update the release-next branch in preparation for the 1.11 release
  components/docs/VersionSelect.jsx
  content/docs/installation/supported-releases.md
  content/docs/release-notes/release-notes-0.1.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
  content/next-docs/configuration/acme/README.md
  content/next-docs/installation/supported-releases.md
  content/next-docs/manifest.json
  content/next-docs/release-notes/release-notes-0.1.md
  content/next-docs/release-notes/release-notes-1.10.md
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, cherry-pick-approved, size/L

#1137 Add an x-robots-tag: noindex header for all branch deploys
  custom-headers/branch-deploy-site-headers
  netlify.toml
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm

#1129 Release notes 1.11
  .spelling
  content/docs/installation/upgrading/upgrading-1.10-1.11.md
  content/docs/manifest.json
  content/docs/release-notes/README.md
  content/docs/release-notes/release-notes-1.11.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/L

#1120 An Azure AKS + Let's Encrypt Tutorial
  README.md
  components/docs/VersionSelect.jsx
  content/docs/configuration/acme/dns01/azuredns.md
  content/docs/getting-started/README.md
  content/docs/manifest.json
  content/docs/release-notes/release-notes-1.11.md
  content/docs/tutorials/README.md
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/certificate.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/clusterissuer-lets-encrypt-staging.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/clusterissuer-selfsigned.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/deployment.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/service.yaml
  public/docs/tutorials/getting-started-with-cert-manager-on-azure-kubernetes-service-using-lets-encrypt-for-ssl/values.yaml
  public/images/icons/azure_kubernetes_service.svg
Labels: approved, dco-signoff: yes, size/XXL, cherry-pick-approved, lgtm

#1143 Several improvements to release process
  .spelling
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1142 Release notes for 1.10.2
  content/docs/installation/README.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/release-notes/release-notes-1.10.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1144 Move CA bundle note from next-docs on master branch to docs/ ...
  content/docs/configuration/acme/README.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#1032 projects/approver-policy: selector.namespace
  content/docs/projects/approver-policy.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1140 Fix Azure AKS tutorial file downloads
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  public/docs/tutorials/getting-started-aks-letsencrypt/certificate.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/clusterissuer-lets-encrypt-staging.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/clusterissuer-selfsigned.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/deployment.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/service.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/values.yaml
Labels: approved, size/XS, dco-signoff: yes, cherry-pick-approved, lgtm

#1141 fix: missing word in sentence, updated all versions present
  content/docs/installation/kubectl.md
  content/next-docs/installation/kubectl.md
  content/v1.10-docs/installation/kubectl.md
  content/v1.9-docs/installation/kubectl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1139 docs: remove incorrect backtick from csr example
  content/docs/reference/cmctl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1130 Expand Google Workload Identity section with a note about Ambient Credentials
  content/docs/configuration/acme/dns01/google.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1149 Merge master
  .spelling
  content/docs/configuration/acme/dns01/google.md
  content/docs/contributing/release-process.md
  content/docs/installation/README.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/projects/approver-policy.md
  content/docs/reference/cmctl.md
  content/docs/release-notes/release-notes-1.10.md
  content/v1.10-docs/installation/kubectl.md
  content/v1.9-docs/installation/kubectl.md
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1148 Install v1.11.0
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/S

#1151 Add more prose + upgrade instructions for release 1.11
  .spelling
  content/docs/installation/upgrading/upgrading-1.10-1.11.md
  content/docs/release-notes/release-notes-1.11.md
Labels: approved, dco-signoff: yes, cherry-pick-approved, lgtm, size/M

#1147 Add note on milestone / test config updates
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1084 fix: navigation menu hiding search results
  components/Header.jsx
  styles/global.scss
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1152 add outside alert handler
  components/Header.jsx
  lib/useOutsideClick.js
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#1154 fix: dir name is installation not install
  content/docs/reference/cmctl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1155 Update meeting link on site
  content/docs/contributing/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1157 feat(docs): update typo in venafi doc
  content/docs/configuration/venafi.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1156 Upgrade all JavaScript dependencies
  components/Button.jsx
  components/Footer.jsx
  components/Header.jsx
  components/Image.jsx
  components/docs/Sidebar/SidebarLink.jsx
  components/docs/VersionSelect.jsx
  lib/remark-plugins/heading-ids/index.js
  lib/remark-plugins/import/index.js
  next-sitemap.config.js
  next.config.js
  package-lock.json
  package.json
  pages/index.jsx
  pages/support.jsx
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1162 Fix/improve csi-driver-spiffe docs
  content/docs/projects/csi-driver-spiffe.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1153 add 404 page
  pages/404.jsx
  public/images/cert-manager-404-illustration.svg
Labels: approved, dco-signoff: yes, lgtm, size/M, ok-to-test

#1166 Use include files for tutorial manifests
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  lib/remark-plugins/import/index.js
  lib/serialize.js
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1167 Run the link check for PRs and changes to master
  .github/workflows/check.yaml
  README.md
  content/docs/concepts/issuer.md
  content/docs/concepts/webhook.md
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/installation/upgrading/upgrading-0.16-1.0.md
  content/docs/projects/approver-policy.md
  content/docs/projects/csi-driver.md
  content/docs/reference/cmctl.md
  content/docs/release-notes/release-notes-0.16.md
  content/docs/release-notes/release-notes-1.0.md
  content/docs/release-notes/release-notes-1.11.md
  content/docs/troubleshooting/acme.md
  content/docs/tutorials/acme/nginx-ingress.md
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  content/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/README.md
  content/docs/tutorials/istio-csr/istio-csr.md
  content/docs/usage/approver-policy.md
  content/docs/usage/certificate.md
  content/docs/usage/csi.md
  content/docs/usage/istio.md
  content/docs/usage/kube-csr.md
  markdown-link-check.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#1169 Various website updates
  components/docs/Sidebar/Dropdown.jsx
  components/docs/VersionSelect.jsx
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
  content/docs/reference/api-docs.md
  content/v1.10-docs/reference/api-docs.md
  content/v1.11-docs/cli/controller.md
  content/v1.11-docs/cli/webhook.md
  content/v1.11-docs/reference/api-docs.md
  content/v1.11-docs/reference/cmctl.md
  content/v1.8-docs/reference/api-docs.md
  content/v1.9-docs/reference/api-docs.md
  scripts/gendocs/generate-new-import-path-docs
  scripts/gendocs/postprocess/api-doc-postprocess.js
  scripts/gendocs/templates/members.tpl
  scripts/gendocs/templates/pkg.tpl
  scripts/gendocs/templates/type.tpl
Labels: approved, dco-signoff: yes, lgtm, size/L

#1170 Trust manager API doc generation
  .spelling
  content/docs/configuration/ca.md
  content/docs/configuration/selfsigned.md
  content/docs/manifest.json
  content/docs/projects/README.md
  content/docs/projects/trust-manager/README.md
  content/docs/projects/trust-manager/api-reference.md
  scripts/bin/crdoc
  scripts/gendocs/generate
  scripts/gendocs/generate-trust-manager
  scripts/gendocs/templates-trust-manager/markdown.tmpl
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1172 Add an installation / best-practice page
  content/docs/installation/best-practice.md
  content/docs/manifest.json
  public/docs/installation/best-practice/values.best-practice.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1171 Reword intro for csi-driver-spiffe
  content/docs/projects/csi-driver-spiffe.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1173 A note about disabling branch protection for some of the release steps
  content/docs/contributing/release-process.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
