Repository cert-manager/website, pull requests merged in 2023-03, with the labels that each got.

#1193 Explains what happens if CertificateRequest is denied
  content/docs/projects/approver-policy.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1081 Vault: document the new field "serviceAccountRef"
  .spelling
  content/docs/configuration/vault.md
  content/docs/manifest.json
  content/docs/release-notes/README.md
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1200 Remove unused script and references to deleted npm update script
  scripts/gendocs/generate-new-import-path-docs
  scripts/gendocs/generate-old-import-path-docs
  scripts/index
Labels: approved, dco-signoff: yes, lgtm, size/M

#1203 Clarify ingress-shim annotations
  content/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1183 Docs: Clarify zeroSSL setup instructions
  content/docs/tutorials/zerossl/zerossl.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1205 Installation note about gke autopilot
  content/docs/installation/compatibility.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1206 Fix typos / some wording for approver-policy docs
  content/docs/installation/compatibility.md
  content/docs/projects/approver-policy.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1196 Document the `ingressClassName` field
  content/docs/configuration/acme/README.md
  content/docs/configuration/acme/http01/README.md
  content/docs/installation/upgrading/ingress-class-compatibility.md
  content/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/docs/reference/api-docs.md
  content/docs/release-notes/release-notes-1.12.md
  content/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/docs/tutorials/acme/example/ingress-tls.yaml
  content/docs/tutorials/acme/example/ingress.yaml
  content/docs/tutorials/acme/example/pomerium-production-issuer.yaml
  content/docs/tutorials/acme/example/pomerium-staging-issuer.yaml
  content/docs/tutorials/acme/example/production-issuer.yaml
  content/docs/tutorials/acme/example/staging-issuer.yaml
  content/docs/tutorials/acme/http-validation.md
  content/docs/tutorials/acme/migrating-from-kube-lego.md
  content/docs/tutorials/venafi/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/L
