Repository cert-manager/website, pull requests merged in 2023-12, with the labels that each got.

#1354 Add FAQ entry on keystore passwords
  content/docs/faq/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1358 added doc for CA name constraints
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1359 Add erikgb to project reviewers
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1361 Release notes and updates for v1.13.3
  .spelling
  content/docs/cli/controller.md
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/releases/release-notes/release-notes-1.13.md
  content/v1.13-docs/installation/README.md
  content/v1.13-docs/installation/code-signing.md
  content/v1.13-docs/installation/helm.md
  content/v1.13-docs/installation/kubectl.md
  content/v1.13-docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1360 Verify Mastodon social media link
  components/Header.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1365 Release notes and updates for cert manager v1.12.7
  .spelling
  content/docs/releases/release-notes/release-notes-1.12.md
  content/v1.12-docs/installation/README.md
  content/v1.12-docs/installation/code-signing.md
  content/v1.12-docs/installation/helm.md
  content/v1.12-docs/installation/kubectl.md
  content/v1.12-docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1363 Adjust the release process: Sign off the cmd/ctl and push the tag only after merging the PR
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1366 Update supported releases to match latest known details
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1367 Fixing link to 1.12 LTS release notes
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1369 adding new version of adcs-issuer
  content/docs/configuration/issuers.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1373 Venafi Issuer: Explain why "Do not select 'refresh token enabled'"
  content/docs/configuration/venafi.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
