Repository cert-manager/website, pull requests merged in 2023-09, with the labels that each got.

#1275 Renaming all references to jetstack/testing
  README.md
  content/docs/contributing/e2e.md
  content/docs/contributing/release-process.md
  content/v1.12-docs/contributing/e2e.md
  content/v1.12-docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1277 [Release v1.11.5 and v1.12.4]: Add release notes
  .spelling
  content/docs/reference/api-docs.md
  content/docs/release-notes/release-notes-1.11.md
  content/docs/release-notes/release-notes-1.12.md
  content/v1.12-docs/reference/api-docs.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1242 Provide link to Zilore webhook
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1267 Update apiVersion in zeroSSL ClusterIssuer example
  content/docs/tutorials/zerossl/zerossl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1251 Add queried endpoint to check Vault status when initializing issuer
  content/docs/configuration/vault.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1005 Route53 accessKeyIDSecretRef docs
  content/docs/configuration/acme/dns01/route53.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#1244 document new subject ingress/gateway annotations
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1235 Add deletion of validatingwebhookconfigurations to stuck uninstall
  content/docs/installation/kubectl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#446 Add multiple ingresses usage section
  content/docs/usage/ingress.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test

#1284 Fix broken kyverno links
  content/docs/installation/best-practice.md
  content/v1.12-docs/installation/best-practice.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1282 Rename the "Configuration" and "Usage" top-level menu items
  content/docs/configuration/venafi.md
  content/docs/manifest.json
  content/docs/tutorials/venafi/venafi.md
  content/docs/usage/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1288 Add the source of the PNG shown in https://cert-manager.io/docs/concepts/certificate/
  public/images/letsencrypt-flow-cert-manager.drawio
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1287 Use same method for creating on-page references links across all pages
  content/docs/configuration/acme/README.md
  content/docs/configuration/acme/http01/README.md
  content/docs/faq/README.md
  content/docs/installation/supported-releases.md
  content/docs/troubleshooting/webhook.md
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1292 Update release and support details for 1.13 release
  content/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1285 [Release v1.12.4]: update installation instructions to 1.12.4
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1293 Add bulletpoint for stackit webhook
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1298 Add upgrade notes for 1.13
  content/docs/installation/upgrading/upgrading-1.12-1.13.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1296 Add 1.13 release notes
  .spelling
  content/docs/manifest.json
  content/docs/release-notes/README.md
  content/docs/release-notes/release-notes-1.13.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1299 Add upgrade notes to the manifest.json file
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1278 Add clarification to selfsigned bootstrapping
  .spelling
  content/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1301 Update csi-driver project page
  content/docs/projects/csi-driver.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1300 Add ejbca-issuer to external issuers list
  .spelling
  content/docs/configuration/external.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1302 Update feature flags page to reflect changes made in 1.13
  .spelling
  content/docs/installation/featureflags.md
  content/v1.13-docs/installation/featureflags.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1306 Add 1.12.5 release notes
  .spelling
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1307 Add 1.13.1 release notes
  .spelling
  content/docs/release-notes/release-notes-1.13.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1305 Update latest cm version from v1.13.0 to v1.13.1
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/v1.13-docs/installation/README.md
  content/v1.13-docs/installation/code-signing.md
  content/v1.13-docs/installation/helm.md
  content/v1.13-docs/installation/kubectl.md
  content/v1.13-docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1308 Update 1.12 installation docs to refer to latest patch release
  content/v1.12-docs/installation/README.md
  content/v1.12-docs/installation/code-signing.md
  content/v1.12-docs/installation/helm.md
  content/v1.12-docs/installation/kubectl.md
  content/v1.12-docs/installation/operator-lifecycle-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1309 Restructure top-level menu
  .spelling
  content/docs/concepts/certificate.md
  content/docs/configuration/ca.md
  content/docs/configuration/selfsigned.md
  content/docs/contributing/projects.md
  content/docs/devops-tips/backup.md
  content/docs/devops-tips/prometheus-metrics.md
  content/docs/devops-tips/syncing-secrets-across-namespaces.md
  content/docs/installation/uninstall.md
  content/docs/installation/upgrading/README.md
  content/docs/installation/upgrading/upgrading-0.10-0.11.md
  content/docs/installation/upgrading/upgrading-0.16-1.0.md
  content/docs/installation/upgrading/upgrading-0.5-0.6.md
  content/docs/installation/upgrading/upgrading-0.8-0.9.md
  content/docs/installation/upgrading/upgrading-1.1-1.2.md
  content/docs/manifest.json
  content/docs/policy/README.md
  content/docs/policy/approval/README.md
  content/docs/policy/approval/approver-policy/README.md
  content/docs/policy/approval/approver-policy/api-reference.md
  content/docs/policy/defaulting.md
  content/docs/policy/issuing.md
  content/docs/trust/README.md
  content/docs/trust/trust-manager/README.md
  content/docs/trust/trust-manager/api-reference.md
  content/docs/tutorials/README.md
  content/docs/tutorials/getting-started-with-trust-manager/README.md
  content/docs/tutorials/istio-csr/istio-csr.md
  content/docs/usage/README.md
  content/docs/usage/approver-policy.md
  content/docs/usage/csi-driver-spiffe.md
  content/docs/usage/csi-driver.md
  content/docs/usage/csi.md
  content/docs/usage/istio-csr.md
  content/docs/usage/istio.md
  package.json
  public/_redirects
  public/images/issuance-flow-policy.png
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, size/XL, lgtm
