Repository cert-manager/website, pull requests merged in 2023-06, with the labels that each got.

#1238 Fix mistake in EOL year
  content/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1239 Explain what FAO stands for
  .spelling
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1217 Document the liveness probes in cert-manager components
  .spelling
  content/docs/installation/best-practice.md
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#982 [GSOD] Define our audiences
  .spelling
  content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1248 Document CRD considerations when using helm
  .spelling
  content/docs/installation/helm.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1212 tutorial: trust-manager distributing public CAs in k8s
  .spelling
  content/docs/manifest.json
  content/docs/tutorials/getting-started-with-trust-manager/README.md
  content/docs/tutorials/getting-started-with-trust-manager/gatekeeper/deploy-novol.yaml
  content/docs/tutorials/getting-started-with-trust-manager/gatekeeper/deploy-withvol.yaml
  content/docs/tutorials/getting-started-with-trust-manager/gatekeeper/gatekeeper-trust-pod-ca-volume.yaml
  content/docs/tutorials/getting-started-with-trust-manager/gatekeeper/gatekeeper-trust-pod-ca-volumemount.yaml
  content/docs/tutorials/getting-started-with-trust-manager/trust/bundle-one-ca.yaml
  content/docs/tutorials/getting-started-with-trust-manager/trust/bundle-public.yaml
  content/docs/tutorials/getting-started-with-trust-manager/trust/deploy-auto.yaml
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1256 Post-release 1.12: add empty upgrade notes
  content/docs/installation/upgrading/upgrading-1.11-1.12.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#1252 fix: https://cert-manager.io/v1.12-docs doesn't work
  content/v1.12-docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#1229 [Release 1.12 + 1.13.0-alpha.0] Update Release Process
  .gitignore
  .spelling
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1254 Add link to CEL approver-policy plugin
  content/docs/projects/approver-policy/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm
