Repository cert-manager/website, pull requests merged in 2023-08, with the labels that each got.

#1264 Add release notes for 1.12.1, 1.12.2 and 1.12.3
  .spelling
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1268 Add release notes for 1.11.2->1.11.4
  .spelling
  content/docs/release-notes/release-notes-1.11.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1269 Annual review of the OWNERS file (2023): remove Joakim
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1270 Fix Venafi broken link
  content/docs/configuration/venafi.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1271 Add docs on trust namespace
  content/docs/projects/trust-manager/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1272 Update supported releases about 1.13
  content/docs/installation/supported-releases.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1273 Annual review of the OWNERS file (2023): Maartje moved to Emeritus Maintainer
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1274 Add docs for trust-manager v0.6.0
  .spelling
  content/docs/projects/trust-manager/README.md
  content/docs/projects/trust-manager/api-reference.md
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/S
