Repository cert-manager/website, pull requests merged in 2023-05, with the labels that each got.

#1218 Add note about linux/arm64 support
  content/docs/contributing/building.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1219 Add more meeting info
  content/docs/contributing/README.md
  content/docs/contributing/google-season-of-docs/README.md
Labels: approved, dco-signoff: yes, size/M

#1208 release-1.11: add a section in the release notes
  .spelling
  content/docs/release-notes/release-notes-1.11.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1223 Add inteon to OWNERS
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1221 Fix a typo in usage/certificate docs
  content/docs/usage/certificate.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1222 Fix leading whitespaces in YAML code block
  content/docs/tutorials/acme/example/production-issuer.yaml
  content/docs/tutorials/acme/example/staging-issuer.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1220 Release notes for 1.12
  .spelling
  content/docs/release-notes/release-notes-0.9.md
  content/docs/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1225 Adds info about cmctl tag
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1228 Add guidelines for writing release notes
  content/docs/contributing/contributing-flow.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1231 [Release 1.12] Merge release-next into master
  .spelling
  content/docs/configuration/acme/README.md
  content/docs/configuration/acme/http01/README.md
  content/docs/configuration/vault.md
  content/docs/installation/upgrading/ingress-class-compatibility.md
  content/docs/installation/upgrading/upgrading-0.7-0.8.md
  content/docs/manifest.json
  content/docs/reference/api-docs.md
  content/docs/release-notes/README.md
  content/docs/release-notes/release-notes-0.9.md
  content/docs/release-notes/release-notes-1.12.md
  content/docs/tutorials/acme/example/ingress-tls-final.yaml
  content/docs/tutorials/acme/example/ingress-tls.yaml
  content/docs/tutorials/acme/example/ingress.yaml
  content/docs/tutorials/acme/example/pomerium-production-issuer.yaml
  content/docs/tutorials/acme/example/pomerium-staging-issuer.yaml
  content/docs/tutorials/acme/example/production-issuer.yaml
  content/docs/tutorials/acme/example/staging-issuer.yaml
  content/docs/tutorials/acme/http-validation.md
  content/docs/tutorials/acme/migrating-from-kube-lego.md
  content/docs/tutorials/venafi/venafi.md
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1232 fix alt tag issue
  components/Feature.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm
