Repository cert-manager/website, pull requests merged in 2024-08, with the labels that each got.

#1530 Add more runtime config notes for istio-csr v0.11.0
  content/docs/usage/istio-csr/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1533 Merge master into release-next
  components/docs/VersionSelect.jsx
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/reference/api-docs.md
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/trust/trust-manager/installation.md
  content/docs/usage/istio-csr/installation.md
  content/docs/variables.json
  public/_redirects
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L

#1537 Add release notes for v1.15.3 and update latest cert-manager version
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/variables.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1539 Add redirect for kubecon NA 2024 QR code link
  public/_redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1540 [CI] Self-upgrade merging self-upgrade-master into master
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
