Repository cert-manager/website, pull requests merged in 2024-07, with the labels that each got.

#1511 Bump npm dependencies
  .eslintrc.json
  .github/workflows/check.yaml
  components/docs/CodeBlock.jsx
  lib/github.js
  lib/remark-plugins/variable/index.js
  netlify.toml
  next.config.js
  package-lock.json
  package.json
  pages/[...docs].jsx
  pages/announcements/[[...article]].jsx
  scripts/build-release
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1512 Add redirects for cert-manager.dev, trust-manager.io and trust-manager.dev
  public/_redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1515 Fix broken links to Prow command help
  content/docs/contributing/contributing-flow.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1518 [CI] Self-upgrade merging self-upgrade-master into master
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1519 Update the release-next branch with latest changes in master
  .eslintrc.json
  .github/workflows/check.yaml
  .github/workflows/make-self-upgrade.yaml
  Makefile
  OWNERS
  OWNERS_ALIASES
  components/docs/CodeBlock.jsx
  content/docs/contributing/contributing-flow.md
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/variables.json
  klone.yaml
  lib/github.js
  lib/remark-plugins/variable/index.js
  make/_shared/generate-verify/00_mod.mk
  make/_shared/generate-verify/02_mod.mk
  make/_shared/generate-verify/util/verify.sh
  make/_shared/help/help.sh
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
  make/_shared/repository-base/base/OWNERS_ALIASES
  make/_shared/tools/00_mod.mk
  make/_shared/tools/util/checkhash.sh
  make/_shared/tools/util/hash.sh
  make/_shared/tools/util/lock.sh
  netlify.toml
  next.config.js
  package-lock.json
  package.json
  pages/[...docs].jsx
  pages/announcements/[[...article]].jsx
  public/_redirects
  scripts/build-release
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1513 Remove $ from bash code snippets
  content/docs/installation/kubectl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1514 Markup shell session snippets as console
  content/docs/installation/kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1521 Add boilerplate for the cert-manager 1.16 release
  content/docs/manifest.json
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/releases/upgrading/upgrading-1.15-1.16.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1523 Document new releases of istio-csr and trust-manager
  content/docs/reference/api-docs.md
  content/docs/trust/trust-manager/installation.md
  content/docs/usage/istio-csr/installation.md
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L

#1522 [VC-34401] Update Prometheus metrics documentation to include information about the webhook
  content/docs/devops-tips/prometheus-metrics.md
  content/docs/releases/release-notes/release-notes-1.16.md
  public/docs/devops-tips/prometheus-metrics/prometheus-status-targets.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#1524 [VC-34401] Update Prometheus metrics documentation to include information about the cainjector
  content/docs/devops-tips/prometheus-metrics.md
  content/docs/releases/release-notes/release-notes-1.16.md
  public/docs/devops-tips/prometheus-metrics/prometheus-status-targets.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#1526 Add release notes for v1.16.0-alpha.0
  content/docs/releases/release-notes/release-notes-1.16.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1525 cert-manager v1.15.2 release notes
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S
