Repository cert-manager/website, pull requests merged in 2024-02, with the labels that each got.

#1399 fix: Update copyright year in footer
  components/Footer.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1407 docs: Revise release note for profile option and add example to the certificate usage section
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1408 Improve OtherNames Release notes
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1409 Add reference links for the new issuingCertificateURLs feature
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1410 Add more cross reference links to the Security items in the release notes
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1411 Release notes for v1.14.1 including explanation for the failed v1.14.0 release
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/releases/upgrading/upgrading-1.13-1.14.md
  content/docs/tutorials/certificate-defaults/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1412 Announce the new cmctl repo on GitHub
  content/docs/reference/cmctl.md
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1400 Release cert-manager 1.14
  .spelling
  content/docs/cli/acmesolver.md
  content/docs/cli/cainjector.md
  content/docs/cli/cmctl.md
  content/docs/cli/controller.md
  content/docs/cli/startupapicheck.md
  content/docs/cli/webhook.md
  content/docs/configuration/acme/http01/README.md
  content/docs/devops-tips/prometheus-metrics.md
  content/docs/installation/README.md
  content/docs/installation/best-practice.md
  content/docs/installation/code-signing.md
  content/docs/installation/configuring-components.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/manifest.json
  content/docs/reference/api-docs.md
  content/docs/reference/cmctl.md
  content/docs/releases/README.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/releases/upgrading/upgrading-1.13-1.14.md
  content/docs/tutorials/README.md
  content/docs/tutorials/certificate-defaults/README.md
  content/docs/usage/certificate.md
  content/docs/usage/gateway.md
  public/docs/tutorials/certificate-defaults/cert-test-minimal.yaml
  public/docs/tutorials/certificate-defaults/cert-test-revision-override.yaml
  public/docs/tutorials/certificate-defaults/cert-test-revision.yaml
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-0.yaml
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-1.yaml
  public/docs/tutorials/certificate-defaults/ingress.yaml
  scripts/gendocs/generate-new-import-path-docs
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1414 Add 1.14 to the supported releases table
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1413 Add docs for approver-policy CEL validations
  content/docs/policy/approval/approver-policy/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1391 add label selector doc
  content/docs/trust/trust-manager/README.md
  content/docs/trust/trust-manager/api-reference.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1415 Regenerate approver-policy API docs
  content/docs/policy/approval/approver-policy/api-reference.md
  scripts/gendocs/generate-approver-policy
  scripts/gendocs/templates-approver-policy/markdown.tmpl
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1420 Release 1.14.2: update release notes, upgrade notes and latest version
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/releases/upgrading/upgrading-1.13-1.14.md
  content/docs/tutorials/certificate-defaults/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1421 Bump hashes for csi-driver-spiffe files
  content/docs/usage/csi-driver-spiffe.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1422 Update Name constraints docs and release notes
  content/docs/installation/configuring-components.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1423 fix: Broken link due to missing character
  content/docs/tutorials/certificate-defaults/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1418 Remove config-sync from cert-manager website
  content/docs/devops-tips/syncing-secrets-across-namespaces.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1424 Update istio-csr installation for Istio >= 1.16
  content/docs/tutorials/istio-csr/example/istio-config-getting-started.yaml
  content/docs/tutorials/istio-csr/istio-csr.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1427 BUGFIX: upgrade links plugin and fix bug in SidebarLink component
  components/docs/Sidebar/SidebarLink.jsx
  lib/remark-plugins/links/index.js
  lib/serialize.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1428 FIX: the startupapicheck CLI docs were missing from the menu
  content/docs/manifest.json
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1071 Improved the summary on the docs homepage
  content/docs/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1429 Document known issue: wrong certificate chain is used if preferredChain is configured
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1430 New patch releases: `v1.12.8`, `v1.13.4` and `v1.14.3`
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.13.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/tutorials/certificate-defaults/README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1426 Split all sub-components documentation onto a separate installation and usage page
  content/docs/README.md
  content/docs/contributing/projects.md
  content/docs/manifest.json
  content/docs/policy/approval/approver-policy/README.md
  content/docs/policy/approval/approver-policy/installation.md
  content/docs/trust/trust-manager/README.md
  content/docs/trust/trust-manager/installation.md
  content/docs/tutorials/README.md
  content/docs/tutorials/istio-csr/example/DEPRECATED.md
  content/docs/usage/README.md
  content/docs/usage/certificate.md
  content/docs/usage/csi-driver-spiffe/README.md
  content/docs/usage/csi-driver-spiffe/installation.md
  content/docs/usage/csi-driver/README.md
  content/docs/usage/csi-driver/installation.md
  content/docs/usage/csi.md
  content/docs/usage/istio-csr/README.md
  content/docs/usage/istio-csr/example/example-cluster-issuer.yaml
  content/docs/usage/istio-csr/example/example-issuer.yaml
  content/docs/usage/istio-csr/example/istio-config-getting-started.yaml
  content/docs/usage/istio-csr/installation.md
  public/_redirects
Labels: approved, dco-signoff: yes, size/XL, lgtm
