Repository cert-manager/website, pull requests merged in 2024-01, with the labels that each got.

#1374 changing release site for adcs-issuer
  content/docs/configuration/issuers.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1371 Update CLI reference
  content/docs/cli/acmesolver.md
  content/docs/cli/cainjector.md
  content/docs/cli/cmctl.md
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
  content/docs/reference/api-docs.md
  scripts/gendocs/generate-new-import-path-docs
Labels: approved, dco-signoff: yes, lgtm, size/L

#1375 Pre-release v1.14.0-alpha.0
  .spelling
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/manifest.json
  content/docs/releases/README.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/releases/upgrading/upgrading-1.13-1.14.md
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1381 Update liveness probe docs
  content/docs/installation/best-practice.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1383 Format the issuers table
  content/docs/configuration/issuers.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1382 Add GlobalSign Atlas Issuer
  .spelling
  content/docs/configuration/issuers.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1377 Fix error in request-certificate diagram
  public/images/request-certificate-overview/request-certificate-cr.svg
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1385 Verify the AKS + LetsEncrypt tutorial
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1384 Update link to code in faqs
  content/docs/faq/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1378 Add Certificate 'otherNames' SAN field description
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1279 docs: Certificate Defaults Tutorial
  .spelling
  content/docs/manifest.json
  content/docs/tutorials/README.md
  content/docs/tutorials/certificate-defaults/README.md
  public/docs/tutorials/certificate-defaults/cert-test-minimal.yaml
  public/docs/tutorials/certificate-defaults/cert-test-revision-override.yaml
  public/docs/tutorials/certificate-defaults/cert-test-revision.yaml
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-0.yaml
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-1.yaml
  public/docs/tutorials/certificate-defaults/ingress.yaml
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1387 Release notes for pre-release v1.14.0 alpha.1
  .spelling
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1199 Webhook troubleshooting: advise people to set `timeoutSeconds` to 30 seconds
  content/docs/troubleshooting/webhook.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1393 Merge master into release-next
  .spelling
  OWNERS
  content/docs/configuration/issuers.md
  content/docs/configuration/venafi.md
  content/docs/faq/README.md
  content/docs/installation/code-signing.md
  content/docs/releases/README.md
  content/docs/troubleshooting/webhook.md
  content/docs/trust/README.md
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  public/images/request-certificate-overview/request-certificate-cr.svg
Labels: approved, dco-signoff: yes, lgtm, size/L

#1394 [release-next] Also verify startupapicheck
  content/docs/installation/code-signing.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1398 Release process updates
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1396 chore: Tutorial component install version increments
  content/docs/tutorials/certificate-defaults/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1401 Add --force-update flag to 'helm repo add' command
  content/docs/installation/helm.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1403 docs: OtherName configuration references updated
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
  content/docs/installation/configuring-components.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1404 Release notes for v1.14.0
  content/docs/cli/controller.md
  content/docs/cli/startupapicheck.md
  content/docs/cli/webhook.md
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/reference/api-docs.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/releases/upgrading/upgrading-1.13-1.14.md
  content/docs/tutorials/certificate-defaults/README.md
  scripts/gendocs/generate-new-import-path-docs
Labels: approved, dco-signoff: yes, size/XL, lgtm
