Repository cert-manager/website, pull requests merged in 2024-05, with the labels that each got.

#1470 Add notes about required tools for macOS
  content/docs/contributing/building.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1477 Rework 1.12 release notes
  content/docs/releases/release-notes/release-notes-1.12.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1478 Update supported releases to reflect actual tests
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1482 Add docs for csi-driver-spiffe v0.6.0
  content/docs/usage/csi-driver-spiffe/README.md
  content/docs/usage/csi-driver-spiffe/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1486 Set the release date for 1.15
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1448 Remove approver-policy versions from install instructions
  content/docs/policy/approval/approver-policy/installation.md
  content/docs/variables.json
Labels: approved, size/XS, dco-signoff: yes, lgtm
