Repository cert-manager/website, pull requests merged in 2024-03, with the labels that each got.

#1433 Introduce variables for versions
  content/docs/contributing/policy.md
  content/docs/installation/README.md
  content/docs/installation/code-signing.md
  content/docs/installation/helm.md
  content/docs/installation/kubectl.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/troubleshooting/webhook.md
  content/docs/tutorials/acme/pomerium-ingress.md
  content/docs/tutorials/certificate-defaults/README.md
  content/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/README.md
  content/docs/tutorials/zerossl/zerossl.md
  content/docs/usage/istio-csr/installation.md
  content/docs/variables.json
  lib/docs.js
  lib/remark-plugins/variable/index.js
  lib/serialize.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1434 Update release process: bump latest version using variable
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1441 Use version variables for the 1.12 and 1.13 docs
  content/v1.12-docs/installation/README.md
  content/v1.12-docs/installation/helm.md
  content/v1.12-docs/installation/kubectl.md
  content/v1.12-docs/installation/operator-lifecycle-manager.md
  content/v1.12-docs/variables.json
  content/v1.13-docs/installation/README.md
  content/v1.13-docs/installation/code-signing.md
  content/v1.13-docs/installation/helm.md
  content/v1.13-docs/installation/kubectl.md
  content/v1.13-docs/installation/operator-lifecycle-manager.md
  content/v1.13-docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1440 Add release notes for v1.14.4, v1.13.5 and v1.12.9
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.13.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1438 approver-policy: improve install instructions and add uninstall instructions
  content/docs/policy/approval/approver-policy/installation.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1437 Update cmctl docs in preparation for v2 release
  content/docs/reference/cmctl.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1443 Add missing period
  content/docs/devops-tips/syncing-secrets-across-namespaces.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1445 trust-manager: add uninstall instructions
  content/docs/trust/trust-manager/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1439 trust-manager: improve install instructions
  content/docs/trust/trust-manager/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1442 kubectl plugin: explain how to get autocompletion
  content/docs/reference/cmctl.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1446 Explain that cmctl x uninstall is now safe by default
  content/docs/reference/cmctl.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1444 Explain why to use priorityClassName: system-cluster-critical in production
  .spelling
  content/docs/installation/best-practice.md
  public/docs/installation/best-practice/values.best-practice.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1453 BUGFIX: javascript bug causing incorrect date in URL
  lib/announcements.js
  public/_redirects
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1451 Scarf Pixels
  content/docs/README.md
  content/v1.0-docs/README.md
  content/v1.1-docs/README.md
  content/v1.10-docs/README.md
  content/v1.11-docs/README.md
  content/v1.12-docs/README.md
  content/v1.13-docs/README.md
  content/v1.2-docs/README.md
  content/v1.3-docs/README.md
  content/v1.4-docs/README.md
  content/v1.5-docs/README.md
  content/v1.6-docs/README.md
  content/v1.7-docs/README.md
  content/v1.8-docs/README.md
  content/v1.9-docs/README.md
  pages/_document.js
  pages/support.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1454 Bump required k8s version for csi-driver
  content/docs/usage/csi-driver/installation.md
  content/docs/usage/csi.md
Labels: approved, dco-signoff: yes, lgtm, size/M
