Repository cert-manager/website, pull requests merged in 2024-06, with the labels that each got.

#1485 Fixing minor typos and missing dots
  content/docs/trust/trust-manager/README.md
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/S, ok-to-test

#1481 Add link to ACME DNS01 webhook for Vercel
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1449 Update install instructions, making them consistent for all sub-projects
  content/docs/installation/helm.md
  content/docs/policy/approval/approver-policy/installation.md
  content/docs/trust/trust-manager/installation.md
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  content/docs/usage/csi-driver-spiffe/installation.md
  content/docs/usage/csi-driver/installation.md
  content/docs/usage/istio-csr/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1491 Update install instructions for v1.15.0 due to new CRD behavior
  content/docs/contributing/release-process.md
  content/docs/installation/continuous-deployment-and-gitops.md
  content/docs/installation/helm.md
  content/docs/installation/upgrade.md
  content/docs/reference/cmctl.md
  content/docs/trust/trust-manager/installation.md
  content/docs/tutorials/certificate-defaults/README.md
  content/docs/tutorials/getting-started-aks-letsencrypt/README.md
  content/docs/tutorials/zerossl/zerossl.md
  content/docs/usage/istio-csr/installation.md
  content/docs/usage/kube-csr.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#1497 Update documentation with new approval Helm chart options
  content/docs/policy/approval/approver-policy/installation.md
  content/docs/usage/certificaterequest.md
  content/docs/usage/csi-driver-spiffe/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1502 Fix broken link in istio-csr docs
  content/docs/usage/istio-csr/README.md
  content/v1.11-docs/projects/istio-csr.md
  content/v1.14-docs/usage/istio-csr/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1503 Update to Venafi support page.
  content/pages/support.mdx
  pages/support.jsx
  public/images/venafi-lts-support.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#1504 Document External Vault secretless auth options (v2)
  .spelling
  content/docs/configuration/vault.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#1506 Add release notes for v1.12.12 and v1.14.7
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.14.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1509 Add release notes for cert-manager v1.15.1 and bump latest version
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S
