Repository cert-manager/website, pull requests merged in 2024-04, with the labels that each got.

#1456 Release Process: cmctl no longer shipped as part of cert-manager releases
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1459 Update supported releases page wording
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1362 Respect rel attributes on <Button>
  components/Button.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1460 helm chart: controller.extraArgs → extraArgs
  content/docs/installation/configuring-components.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1463 Update release process to reflect that most of it is more netural now
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1465 Updates following releases of 1.12.10, 1.13.6, 1.14.5
  .spelling
  content/docs/cli/cainjector.md
  content/docs/contributing/release-process.md
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.13.md
  content/docs/releases/release-notes/release-notes-1.14.md
  content/docs/variables.json
  content/v1.12-docs/variables.json
  content/v1.13-docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1467 Issue #1457
  content/pages/support.mdx
  pages/support.jsx
  public/images/venafi-hero.png
  public/images/venafi-lts-support.png
  public/images/venafi-tls-protect-for-kubernetes.svg
Labels: approved, dco-signoff: yes, lgtm, size/M

#1468 Remove AdditionalCertificateOutputFormats alpha warning
  content/docs/usage/certificate.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1458 Explain how to optimise cert-manager for scale
  .spelling
  content/docs/devops-tips/scaling-cert-manager.md
  content/docs/manifest.json
Labels: approved, dco-signoff: yes, lgtm, size/L
