Repository cert-manager/website, pull requests merged in 2024-09, with the labels that each got.

#1543 fix link
  README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1548 Update note on commonName field
  content/docs/usage/certificate.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1547 Update docs for istio-csr following release of v0.12.0
  content/docs/usage/istio-csr/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1544 [VC-35411] AWS + EKS + Route53 + Let's Encrypt tutorial
  .spelling
  content/docs/configuration/acme/dns01/route53.md
  content/docs/getting-started/README.md
  content/docs/manifest.json
  content/docs/tutorials/README.md
  content/docs/tutorials/getting-started-aws-letsencrypt/README.md
  public/docs/tutorials/getting-started-aws-letsencrypt/certificate.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-staging.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-selfsigned.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/deployment.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/rbac.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/service.yaml
  public/images/icons/amazon_elastic_kubernetes_service.svg
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1562 Updates to release process following latest release
  content/docs/contributing/release-process.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1541 Cview-issuer for cert-manager
  .spelling
  content/docs/configuration/issuers.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1551 Document the new renewBeforePercentage field
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/usage/certificate.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1564 Merge master into release-next
  .github/workflows/make-self-upgrade.yaml
  .spelling
  Makefile
  README.md
  content/docs/configuration/acme/dns01/route53.md
  content/docs/configuration/issuers.md
  content/docs/contributing/release-process.md
  content/docs/getting-started/README.md
  content/docs/manifest.json
  content/docs/releases/README.md
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/tutorials/README.md
  content/docs/tutorials/getting-started-aws-letsencrypt/README.md
  content/docs/usage/certificate.md
  content/docs/usage/gateway.md
  content/docs/usage/istio-csr/installation.md
  content/docs/variables.json
  content/v1.12-docs/variables.json
  klone.yaml
  make/_shared/generate-verify/02_mod.mk
  make/_shared/generate-verify/util/verify.sh
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
  make/_shared/tools/00_mod.mk
  public/_redirects
  public/docs/tutorials/getting-started-aws-letsencrypt/certificate.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-staging.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-selfsigned.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/deployment.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/rbac.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/service.yaml
  public/images/icons/amazon_elastic_kubernetes_service.svg
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1566 Update supported releases to add tested k8s versions
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1565 Release notes updates for cert-manager v1.16.0-beta.0
  .spelling
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#1567 More details about the Route53 changes
  content/docs/releases/release-notes/release-notes-1.16.md
Labels: approved, dco-signoff: yes, lgtm, size/S
