Repository cert-manager/website, pull requests merged in 2024-10, with the labels that each got.

#1568 Update breaking changes details 1.16
  content/docs/releases/release-notes/release-notes-1.16.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1575 Merging master into release-next
  content/docs/releases/README.md
  klone.yaml
  make/_shared/tools/00_mod.mk
Labels: approved, dco-signoff: yes, lgtm, size/M

#1572 Update release notes for WatchListClient feature support
  content/docs/releases/release-notes/release-notes-1.16.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1574 Update supported versions for cert-manager 1.16
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1520 Release cert-manager 1.16
  .spelling
  content/docs/cli/cainjector.md
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
  content/docs/configuration/venafi.md
  content/docs/devops-tips/prometheus-metrics.md
  content/docs/installation/configuring-components.md
  content/docs/manifest.json
  content/docs/reference/api-docs.md
  content/docs/releases/README.md
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/releases/upgrading/upgrading-1.15-1.16.md
  content/docs/usage/certificate.md
  content/docs/variables.json
  public/docs/devops-tips/prometheus-metrics/prometheus-status-targets.png
  scripts/gendocs/generate-new-import-path-docs
  scripts/gendocs/postprocess/api-doc-postprocess.js
Labels: approved, dco-signoff: yes, size/XXL, lgtm

#1578 update external issuers table
  content/docs/configuration/issuers.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1554 Add link to ACME DNS01 webhook for Open Telekom Cloud in docs
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm, ok-to-test

#1580 Update trust-manager API docs
  .spelling
  content/docs/trust/trust-manager/api-reference.md
  scripts/gendocs/generate-trust-manager
  scripts/gendocs/templates-trust-manager/markdown.tmpl
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1584 Release notes 1.16.1
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#1555 Update AWS Route53 documentation to better explain the authentication options
  .spelling
  content/docs/configuration/acme/dns01/route53.md
  content/docs/tutorials/getting-started-aws-letsencrypt/README.md
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1588 [CI] Self-upgrade merging self-upgrade-master into master
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1590 Update supported releases page to reflect expected support for 1.17
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1594 Document the option to includeAllKeys in trust-manager sources
  content/docs/trust/trust-manager/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1595 Add new logo for Venafi, tweak wording
  pages/support.jsx
  public/images/venafi-cybr-logo.png
Labels: approved, dco-signoff: yes, lgtm, size/S
