Repository cert-manager/website, pull requests merged in 2025-04, with the labels that each got.

#1665 Fixed a typo in the trust-manager custom resource example
  content/docs/trust/trust-manager/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1657 Update cert-manager-mixin project
  content/docs/devops-tips/prometheus-metrics.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1656 docs: Fix indenting in code example for acme issuer
  content/docs/configuration/acme/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1516 Clarify differences between example configs for CA issuer and cluster CA issuer
  content/docs/configuration/selfsigned.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1661 announcing Cloudflare MTLS issuer
  .spelling
  content/docs/configuration/issuers.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1668 chore: Add hawksight as an approver
  OWNERS
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1660 Add IONOS Cloud webhook for ACME DNS01 challenge
  content/v1.8-docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1649 acme/dns01/route53: document stricter IAM policy
  content/docs/configuration/acme/dns01/route53.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1673 add IONOS cloud to the list of supported cloud ACME webhook providers
  content/docs/configuration/acme/dns01/README.md
  content/v1.8-docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1674 Release notes for v1.17.2
  content/docs/releases/release-notes/release-notes-1.17.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S, skip-review

#1675 Release notes for v1.16.5
  content/docs/releases/release-notes/release-notes-1.16.md
  content/v1.16-docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S, skip-review

#1677 Release notes for v1.12.17
  content/docs/releases/release-notes/release-notes-1.12.md
  content/v1.12-docs/variables.json
Labels: approved, dco-signoff: yes, size/S

#1676 Added target metadata examples for trust-manager
  content/docs/trust/trust-manager/README.md
  content/docs/trust/trust-manager/api-reference.md
  package.json
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L

#1671 Set copyright year to 2025
  components/Footer.jsx
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1680 Add the boilerplate content for release-1.18 release notes
  content/docs/manifest.json
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/releases/upgrading/upgrading-1.17-1.18.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1501 Document custom annotation behaviour
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
Labels: approved, dco-signoff: yes, lgtm, size/M
