Repository cert-manager/website, pull requests merged in 2025-05, with the labels that each got.

#1685 Docs 1679 follow-up
  README.md
  content/docs/configuration/acme/README.md
  content/docs/configuration/ca.md
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/releases/release-notes/release-notes-1.17.md
  content/v1.14-docs/reference/api-docs.md
  content/v1.15-docs/reference/api-docs.md
  content/v1.15-docs/releases/release-notes/release-notes-1.15.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1689 Add section on CyberArk LTS cert-manager
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1691 chore(docs): typo in issuers.md
  content/docs/configuration/issuers.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1690 Release notes for cert-manager v1.18.0-alpha.0
  content/docs/releases/release-notes/release-notes-1.18.md
Labels: approved, dco-signoff: yes, lgtm, size/M
