Repository cert-manager/website, pull requests merged in 2025-06, with the labels that each got.

#1699 Add new glesys webhook issuer to docs page
  content/docs/configuration/acme/dns01/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1698 Fixed case of 'values.yaml' in Helm installation guide.
  content/docs/installation/helm.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1706 Recategorize the new revisionHistoryLimit as a Potentially breaking change
  content/docs/devops-tips/scaling-cert-manager.md
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/tutorials/certificate-defaults/README.md
  public/docs/tutorials/getting-started-aws-letsencrypt/certificate.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1707 Postpone the release of cert-manager 1.18
  content/docs/releases/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1713 Final changes for the v1.18.0 release
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#1708 Release cert-manager v1.18.0
  .spelling
  content/docs/cli/cainjector.md
  content/docs/cli/controller.md
  content/docs/cli/webhook.md
  content/docs/configuration/acme/README.md
  content/docs/contributing/api-compatibility.md
  content/docs/devops-tips/scaling-cert-manager.md
  content/docs/manifest.json
  content/docs/reference/api-docs.md
  content/docs/releases/README.md
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/releases/upgrading/upgrading-1.17-1.18.md
  content/docs/troubleshooting/acme.md
  content/docs/tutorials/acme/example/production-issuer.yaml
  content/docs/tutorials/acme/example/staging-issuer.yaml
  content/docs/tutorials/acme/nginx-ingress.md
  content/docs/tutorials/certificate-defaults/README.md
  content/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/README.md
  content/docs/usage/certificate.md
  content/docs/usage/gateway.md
  content/docs/usage/ingress.md
  content/docs/variables.json
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-0.yaml
  public/docs/tutorials/certificate-defaults/cpol-mutate-certificates-1.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-aks-letsencrypt/clusterissuer-lets-encrypt-staging.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/certificate.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-production.yaml
  public/docs/tutorials/getting-started-aws-letsencrypt/clusterissuer-lets-encrypt-staging.yaml
  scripts/gendocs/generate-new-import-path-docs
Labels: approved, dco-signoff: yes, size/XL, lgtm

#1714 Document the known issue #7791 and explain that it is due to a bug in ingress-nginx
  content/docs/releases/release-notes/release-notes-1.18.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1720 Release notes for cert-manager v1.18.1
  content/docs/releases/release-notes/release-notes-1.18.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1722 Announce the discontinuation of OperatorHub packages and remove the installation instructions
  content/docs/installation/README.md
  content/docs/installation/operator-lifecycle-manager.md
  content/docs/manifest.json
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/releases/release-notes/release-notes-1.17.md
  content/docs/releases/release-notes/release-notes-1.18.md
  content/docs/releases/release-notes/release-notes-1.4.md
  content/docs/releases/upgrading/upgrading-1.3-1.4.md
  content/v1.17-docs/installation/README.md
  content/v1.17-docs/installation/operator-lifecycle-manager.md
  content/v1.17-docs/manifest.json
Labels: approved, dco-signoff: yes, size/XL, lgtm
