Repository cert-manager/website, pull requests merged in 2025-01, with the labels that each got.

#1618 Update Venafi username/password authentication section
  content/docs/configuration/venafi.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1621 Add release notes for v1.12.15, v1.15.5, v1.16.3
  content/docs/contributing/release-process.md
  content/docs/releases/release-notes/release-notes-1.12.md
  content/docs/releases/release-notes/release-notes-1.15.md
  content/docs/releases/release-notes/release-notes-1.16.md
  content/docs/variables.json
  content/v1.12-docs/variables.json
  content/v1.15-docs/variables.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1626 Fix csi-driver example pod
  content/docs/usage/csi-driver/README.md
Labels: approved, size/XS, dco-signoff: yes, lgtm

#1617 Fix dead external links and update make commands in the contributing doc
  content/docs/contributing/crds.md
  content/docs/installation/best-practice.md
  content/docs/tutorials/README.md
  content/docs/usage/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1628 Revert "Scarf pixels added to main page...
  content/docs/README.md
  content/v1.0-docs/README.md
  content/v1.1-docs/README.md
  content/v1.10-docs/README.md
  content/v1.11-docs/README.md
  content/v1.12-docs/README.md
  content/v1.13-docs/README.md
  content/v1.14-docs/README.md
  content/v1.15-docs/README.md
  content/v1.2-docs/README.md
  content/v1.3-docs/README.md
  content/v1.4-docs/README.md
  content/v1.5-docs/README.md
  content/v1.6-docs/README.md
  content/v1.7-docs/README.md
  content/v1.8-docs/README.md
  content/v1.9-docs/README.md
  pages/_document.js
  pages/support.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1627 Update supported releases
  content/docs/releases/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1631 Update generated docs for trust-manager + approver-policy
  content/docs/policy/approval/approver-policy/api-reference.md
  content/docs/trust/trust-manager/api-reference.md
  scripts/gendocs/generate-approver-policy
  scripts/gendocs/generate-trust-manager
Labels: approved, dco-signoff: yes, lgtm, size/L

#1632 Add script for 'freezing' docs
  README.md
  content/docs/contributing/.x-only-docs
  content/docs/contributing/release-process.md
  content/docs/manifest.json
  content/docs/releases/.x-only-docs
  scripts/freeze-docs
Labels: approved, dco-signoff: yes, lgtm, size/M

#1622 Rework upgrade docs for v1.12
  .spelling
  content/docs/manifest.json
  content/docs/releases/upgrading/upgrading-1.12-1.13.md
  content/docs/releases/upgrading/upgrading-1.12.md
  public/_redirects
Labels: approved, dco-signoff: yes, lgtm, size/L

#1634 Merge release-next into master
  content/docs/trust/trust-manager/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M
